@echo off
chcp 65001 >nul
title GardenPin New Design
cd /d "%~dp0"
echo [1] Building frontend via WSL...
wsl bash -c "cd /mnt/c/Users/Dell\ 5090/Documents/Claude/Projects/Patrik\ The\ Gardener/zahradni-tracker/frontend && npm run build && echo BUILD_OK"
echo [2] Copying dist to backend/public...
wsl bash -c "cd /mnt/c/Users/Dell\ 5090/Documents/Claude/Projects/Patrik\ The\ Gardener/zahradni-tracker && rm -rf backend/public/* && cp -r frontend/dist/* backend/public/ && echo COPY_OK"
echo [3] Killing server...
wsl bash -c "pkill -9 -f node 2>/dev/null || true; sleep 1; echo KILL_OK"
echo [4] Syncing and restarting via kill-a-spustit...
call kill-a-spustit.bat
