// Databáze zahradních rostlin — 80+ druhů
// tasks: pole úkolů které se auto-vytvoří po výběru rostliny
// frequency_days: opakování | specific_month: 1–12 pro jednorázové sezónní úkoly

export const PLANT_DATABASE = [
  // ==================== ZELENINA ====================
  {
    id: 1,
    nameCz: 'Rajče',
    nameLat: 'Solanum lycopersicum',
    soil: 'Výživná, propustná, bohatá na humus, pH 6–6,8',
    sun: '☀️ Plné slunce (min. 6 h)',
    watering: '2–3× týdně, u kořene, bez smáčení listů',
    fertilizing: 'Každých 10–14 dní od nasazení plodů',
    pruning: 'Pravidelně odstraňovat pasínky (postranní výhony)',
    planting: 'Po 15. května (bez mrazu)',
    notes: 'Vázat na tyčky. Preventivně postřikovat proti plísni bramborové.',
    tasks: [
      { title: 'Zálivka rajčat', task_type: 'zalivka', frequency_days: 3, notes: 'U kořene, ne listí' },
      { title: 'Hnojení rajčat', task_type: 'hnojeni', frequency_days: 12, notes: 'Rajčatové hnojivo s draslíkem' },
      { title: 'Pasínkování rajčat', task_type: 'strihani', frequency_days: 7, notes: 'Odlomit výhony v úžlabí listů' },
      { title: 'Kontrola plísně a škůdců', task_type: 'kontrola', frequency_days: 7 },
    ],
  },
  {
    id: 2,
    nameCz: 'Paprika',
    nameLat: 'Capsicum annuum',
    soil: 'Propustná, výživná, pH 6–7',
    sun: '☀️ Plné slunce',
    watering: '2× týdně, vlhká ale ne mokrá půda',
    fertilizing: 'Každých 14 dní dusíko-draselným hnojivem',
    pruning: 'Pinzovat vršky pro větvení',
    planting: 'Po 20. května do krytého nebo teplého místa',
    notes: 'Nesnáší mráz ani přímý vítr. Ideální teplota 20–25 °C.',
    tasks: [
      { title: 'Zálivka papriky', task_type: 'zalivka', frequency_days: 4 },
      { title: 'Hnojení papriky', task_type: 'hnojeni', frequency_days: 14 },
      { title: 'Kontrola škůdců', task_type: 'kontrola', frequency_days: 10 },
    ],
  },
  {
    id: 3,
    nameCz: 'Okurka salátová',
    nameLat: 'Cucumis sativus',
    soil: 'Lehká, humózní, teplá',
    sun: '☀️ Plné slunce, chráněné od větru',
    watering: 'Denně nebo ob den, teplou vodou',
    fertilizing: 'Každých 10 dní dusíkatým hnojivem',
    pruning: 'Pinzovat po 5. listu, odstraňovat postranní výhony',
    planting: 'Po 15. května, teplá půda min. 15 °C',
    notes: 'Sklízet pravidelně, jinak okurky žloutnou a rostlina přestane plodit.',
    tasks: [
      { title: 'Zálivka okurky', task_type: 'zalivka', frequency_days: 2, notes: 'Teplá voda, ne studená' },
      { title: 'Hnojení okurky', task_type: 'hnojeni', frequency_days: 10 },
      { title: 'Sklizeň okurek', task_type: 'sklizen', frequency_days: 3, notes: 'Sbírat dokud jsou zelené' },
      { title: 'Kontrola padlí', task_type: 'kontrola', frequency_days: 7 },
    ],
  },
  {
    id: 4,
    nameCz: 'Salát hlávkový',
    nameLat: 'Lactuca sativa',
    soil: 'Vlhká, humózní, lehká',
    sun: '⛅ Polostín až slunce',
    watering: 'Každý 2–3 dny, rovnoměrně',
    fertilizing: 'Předsadbové hnojení kompostem, v průběhu jen výjimečně',
    pruning: 'Sklízet celou hlávku nebo vnější listy',
    planting: 'Brzy zjara (konec března) nebo na podzim',
    notes: 'V horku rychle vykvétá — preferuje chladnější počasí.',
    tasks: [
      { title: 'Zálivka salátu', task_type: 'zalivka', frequency_days: 2 },
      { title: 'Kontrola salátu', task_type: 'kontrola', frequency_days: 5, notes: 'Hlídat vykvétání (šíp)' },
      { title: 'Sklizeň salátu', task_type: 'sklizen', frequency_days: 7 },
    ],
  },
  {
    id: 5,
    nameCz: 'Mrkev',
    nameLat: 'Daucus carota',
    soil: 'Hluboká, lehká, bez kamenů',
    sun: '☀️ Slunce',
    watering: '1–2× týdně, rovnoměrně',
    fertilizing: 'Draselné hnojivo, bez čerstvého hnoje (větví kořen)',
    pruning: 'Projednávat husté výsevy',
    planting: 'Duben–červen přímo do záhonu',
    notes: 'Prokypřovat půdu do hloubky 30 cm. Proprořit na 5 cm rozestupy.',
    tasks: [
      { title: 'Zálivka mrkve', task_type: 'zalivka', frequency_days: 5 },
      { title: 'Pletí mrkve', task_type: 'plet', frequency_days: 10 },
      { title: 'Prořezání výsevu', task_type: 'strihani', frequency_days: 14, notes: 'Nechat 5 cm mezi rostlinami' },
    ],
  },
  {
    id: 6,
    nameCz: 'Cibule kuchyňská',
    nameLat: 'Allium cepa',
    soil: 'Lehká, propustná, pH 6–7',
    sun: '☀️ Plné slunce',
    watering: 'Méně, v červenci přestat (zrání cibulí)',
    fertilizing: 'Fosforečné hnojivo na jaře',
    pruning: 'Nezasahovávat',
    planting: 'Sazečka: březen–duben. Přímý výsev: březen.',
    notes: 'Netolerantní vůči plevelům — pravidelně plít. Sklízet po poléhání natě.',
    tasks: [
      { title: 'Zálivka cibule', task_type: 'zalivka', frequency_days: 7 },
      { title: 'Pletí cibule', task_type: 'plet', frequency_days: 10 },
      { title: 'Kontrola cibule', task_type: 'kontrola', frequency_days: 14 },
    ],
  },
  {
    id: 7,
    nameCz: 'Česnek',
    nameLat: 'Allium sativum',
    soil: 'Lehká, humózní, dobře propustná',
    sun: '☀️ Plné slunce',
    watering: 'Mírně, v červnu přestat',
    fertilizing: 'Kompost při výsadbě, případně dusík na jaře',
    pruning: 'Odstraňovat stvoly (šla) pro větší hlávky',
    planting: 'Podzim (říjen): ozimý česnek. Jaro (březen): jarní.',
    notes: 'Výborný repelent proti mšicím. Nekombinovat se salátem ani hráškem.',
    tasks: [
      { title: 'Zálivka česneku', task_type: 'zalivka', frequency_days: 7 },
      { title: 'Odstraňování šla', task_type: 'strihani', frequency_days: 10, notes: 'Stvoly do 10 cm — stříhat, zbytek nechat' },
      { title: 'Pletí česneku', task_type: 'plet', frequency_days: 14 },
    ],
  },
  {
    id: 8,
    nameCz: 'Dýně hokkaidó',
    nameLat: 'Cucurbita maxima',
    soil: 'Výživná, humózní, teplá',
    sun: '☀️ Plné slunce',
    watering: '1–2× týdně hojně, u kořene',
    fertilizing: 'Každých 14 dní dusíkatým hnojivem do konce července',
    pruning: 'Zkracovat výhony, nechat 2–3 plody na rostlinu',
    planting: 'Po 20. května, potřebuje hodně místa',
    notes: 'Sklízet před prvními mrazíky. Kůra musí být tuhá.',
    tasks: [
      { title: 'Zálivka dýně', task_type: 'zalivka', frequency_days: 4, notes: 'Hojně, u kořene' },
      { title: 'Hnojení dýně', task_type: 'hnojeni', frequency_days: 14 },
      { title: 'Zkracování výhonů', task_type: 'strihani', frequency_days: 14 },
    ],
  },
  {
    id: 9,
    nameCz: 'Cuketa',
    nameLat: 'Cucurbita pepo',
    soil: 'Humózní, výživná',
    sun: '☀️ Slunce',
    watering: '2–3× týdně hojně',
    fertilizing: 'Každých 14 dní',
    pruning: 'Stačí odstraňovat staré listy',
    planting: 'Konec května',
    notes: 'Sklízet cukety malé (15–20 cm) pro nejlepší chuť. Rostlina je velmi produktivní.',
    tasks: [
      { title: 'Zálivka cukety', task_type: 'zalivka', frequency_days: 3 },
      { title: 'Hnojení cukety', task_type: 'hnojeni', frequency_days: 14 },
      { title: 'Sklizeň cukety', task_type: 'sklizen', frequency_days: 4, notes: 'Sklízet při délce 15–20 cm' },
    ],
  },
  {
    id: 10,
    nameCz: 'Fazole keříčková',
    nameLat: 'Phaseolus vulgaris',
    soil: 'Propustná, středně výživná',
    sun: '☀️ Slunce',
    watering: '2× týdně, zejména při kvetení',
    fertilizing: 'Minimálně — váže dusík sama',
    pruning: 'Není potřeba',
    planting: 'Květen, přímo do záhonu po 8 cm',
    notes: 'Nekombinovat s cibulí. Dobré před-plodiny: mrkev, okurka.',
    tasks: [
      { title: 'Zálivka fazolí', task_type: 'zalivka', frequency_days: 4 },
      { title: 'Sklizeň fazolí', task_type: 'sklizen', frequency_days: 5, notes: 'Sklízet zelené lusky' },
      { title: 'Kontrola škůdců', task_type: 'kontrola', frequency_days: 10 },
    ],
  },
  {
    id: 11,
    nameCz: 'Hrášek zahradní',
    nameLat: 'Pisum sativum',
    soil: 'Humózní, propustná, pH 6–7',
    sun: '☀️ Slunce, toleruje polostín',
    watering: 'Mírně, zejména při kvetení',
    fertilizing: 'Málo — váže vzdušný dusík',
    pruning: 'Opory pro pnoucí odrůdy',
    planting: 'Konec března až duben, snáší lehké mrazy',
    notes: 'Sít brzy na jaře pro lepší výnos. Podpory pro tyčkové odrůdy.',
    tasks: [
      { title: 'Zálivka hrášku', task_type: 'zalivka', frequency_days: 5 },
      { title: 'Sklizeň hrášku', task_type: 'sklizen', frequency_days: 4, notes: 'Sklízet nazelena před plným dozráním' },
    ],
  },
  {
    id: 12,
    nameCz: 'Špenát',
    nameLat: 'Spinacia oleracea',
    soil: 'Výživná, humózní, vlhká',
    sun: '⛅ Polostín (v létě špatný, v jaru a na podzim ideální)',
    watering: 'Rovnoměrně, nevysychat',
    fertilizing: 'Dusíkaté hnojivo při výsadbě',
    pruning: 'Sklízet vnější listy',
    planting: 'Březen–duben nebo srpen–září',
    notes: 'V horku rychle vykvétá. Sít co nejdříve na jaře nebo na podzim.',
    tasks: [
      { title: 'Zálivka špenátu', task_type: 'zalivka', frequency_days: 3 },
      { title: 'Sklizeň špenátu', task_type: 'sklizen', frequency_days: 7 },
    ],
  },
  {
    id: 13,
    nameCz: 'Brokolice',
    nameLat: 'Brassica oleracea var. italica',
    soil: 'Výživná, středně těžká, pH 6,5–7,5',
    sun: '☀️ Slunce',
    watering: '2× týdně rovnoměrně',
    fertilizing: 'Dusíkové hnojivo v červnu',
    pruning: 'Sklízet centrální hlávku pro postranní odnože',
    planting: 'Přesazovat v dubnu–květnu',
    notes: 'Po sklizení centrální hlávky vypučí postranní, které lze opakovaně sklízet.',
    tasks: [
      { title: 'Zálivka brokolice', task_type: 'zalivka', frequency_days: 4 },
      { title: 'Hnojení brokolice', task_type: 'hnojeni', frequency_days: 21 },
      { title: 'Kontrola housenek', task_type: 'kontrola', frequency_days: 7 },
      { title: 'Sklizeň brokolice', task_type: 'sklizen', frequency_days: 7 },
    ],
  },
  {
    id: 14,
    nameCz: 'Kedlubna',
    nameLat: 'Brassica oleracea var. gongylodes',
    soil: 'Středně těžká, výživná',
    sun: '☀️ Slunce, toleruje polostín',
    watering: 'Pravidelně, rovnoměrně',
    fertilizing: 'Kompost před výsadbou',
    pruning: 'Není potřeba',
    planting: 'Duben–červen, přesazovat i přímo sít',
    notes: 'Sklízet při průměru 6–8 cm — větší jsou dřevnaté.',
    tasks: [
      { title: 'Zálivka kedlubny', task_type: 'zalivka', frequency_days: 4 },
      { title: 'Sklizeň kedlubny', task_type: 'sklizen', frequency_days: 7 },
    ],
  },
  {
    id: 15,
    nameCz: 'Zelí bílé',
    nameLat: 'Brassica oleracea var. capitata',
    soil: 'Těžší, výživná, pH 6,5–7,5',
    sun: '☀️ Slunce',
    watering: 'Pravidelně hojně, zejména v létě',
    fertilizing: 'Dusíkaté hnojivo ve dvou dávkách',
    pruning: 'Není potřeba',
    planting: 'Přesazovat v dubnu–květnu',
    notes: 'Hlídat housatka bělásků — sbírat vejce z rubu listů.',
    tasks: [
      { title: 'Zálivka zelí', task_type: 'zalivka', frequency_days: 5 },
      { title: 'Hnojení zelí', task_type: 'hnojeni', frequency_days: 21 },
      { title: 'Kontrola housenek', task_type: 'kontrola', frequency_days: 7 },
    ],
  },
  {
    id: 16,
    nameCz: 'Pórek',
    nameLat: 'Allium porrum',
    soil: 'Výživná, hluboká, propustná',
    sun: '☀️ Slunce',
    watering: '1–2× týdně',
    fertilizing: 'Dusíkaté hnojivo v červnu',
    pruning: 'Obrývat pro bílání',
    planting: 'Přesazovat v červnu',
    notes: 'Obrývat postupně pro delší bílou část.',
    tasks: [
      { title: 'Zálivka pórku', task_type: 'zalivka', frequency_days: 5 },
      { title: 'Hnojení pórku', task_type: 'hnojeni', frequency_days: 21 },
      { title: 'Obrývání pórku', task_type: 'jine', frequency_days: 14, notes: 'Nahrnovat zeminu ke stonku pro bílání' },
    ],
  },
  {
    id: 17,
    nameCz: 'Ředkev / Ředkvička',
    nameLat: 'Raphanus sativus',
    soil: 'Lehká, propustná',
    sun: '☀️ Slunce',
    watering: 'Pravidelně, nevysychat',
    fertilizing: 'Kompost před výsevem',
    pruning: 'Není potřeba',
    planting: 'Březen–srpen, opakovaně každé 2–3 týdny',
    notes: 'Rychlý růst — sklízet do 4 týdnů. Nevhodný pro přímé léto (pálivé).',
    tasks: [
      { title: 'Zálivka ředkviček', task_type: 'zalivka', frequency_days: 2 },
      { title: 'Sklizeň ředkviček', task_type: 'sklizen', frequency_days: 7 },
    ],
  },
  {
    id: 18,
    nameCz: 'Mangold',
    nameLat: 'Beta vulgaris var. cicla',
    soil: 'Výživná, humózní',
    sun: '☀️ Slunce, toleruje polostín',
    watering: '2× týdně',
    fertilizing: 'Dusíkaté hnojivo v průběhu sezóny',
    pruning: 'Sklízet vnější listy',
    planting: 'Duben–červen',
    notes: 'Velmi výnosný — sklizí vnějších listů povzbudí nový růst.',
    tasks: [
      { title: 'Zálivka mangoldu', task_type: 'zalivka', frequency_days: 4 },
      { title: 'Sklizeň mangoldu', task_type: 'sklizen', frequency_days: 7 },
    ],
  },
  {
    id: 19,
    nameCz: 'Petržel kořenová',
    nameLat: 'Petroselinum crispum var. tuberosum',
    soil: 'Hluboká, propustná, bez kamenů',
    sun: '☀️ Slunce, toleruje polostín',
    watering: 'Pravidelně mírně',
    fertilizing: 'Draselné hnojivo, bez dusíku (kořen se větví)',
    pruning: 'Odstraňovat staré listy',
    planting: 'Duben, přímo do záhonu',
    notes: 'Klíčí pomalu — 3 týdny. Prosít půdu do hloubky 25 cm.',
    tasks: [
      { title: 'Zálivka petržele', task_type: 'zalivka', frequency_days: 5 },
      { title: 'Pletí petržele', task_type: 'plet', frequency_days: 10 },
    ],
  },
  {
    id: 20,
    nameCz: 'Tykev (Patison)',
    nameLat: 'Cucurbita pepo var. clypeata',
    soil: 'Výživná, teplá',
    sun: '☀️ Plné slunce',
    watering: '2–3× týdně hojně',
    fertilizing: 'Každých 14 dní',
    pruning: 'Odstraňovat staré listy',
    planting: 'Konec května',
    notes: 'Dekorativní i jedlé. Sklízet mladé pro nejlepší chuť.',
    tasks: [
      { title: 'Zálivka patisonu', task_type: 'zalivka', frequency_days: 3 },
      { title: 'Hnojení patisonu', task_type: 'hnojeni', frequency_days: 14 },
      { title: 'Sklizeň patisonu', task_type: 'sklizen', frequency_days: 5 },
    ],
  },

  // ==================== OVOCE ====================
  {
    id: 21,
    nameCz: 'Jahodník',
    nameLat: 'Fragaria × ananassa',
    soil: 'Lehká, humózní, propustná, pH 5,5–6,5',
    sun: '☀️ Plné slunce',
    watering: '2–3× týdně, ne na plody',
    fertilizing: 'Hnojení po sklizni a na jaře',
    pruning: 'Po sklizni odstranit staré listy a šlahouny',
    planting: 'Srpen–září pro příští rok, nebo jaro',
    notes: 'Zakrývat mulčem pro udržení vlhkosti a čistoty plodů.',
    tasks: [
      { title: 'Zálivka jahod', task_type: 'zalivka', frequency_days: 3 },
      { title: 'Hnojení jahod', task_type: 'hnojeni', frequency_days: 30, notes: 'Po sklizni a na jaře' },
      { title: 'Sklizeň jahod', task_type: 'sklizen', frequency_days: 2, notes: 'Sklízet červené, přezrálé opustit' },
      { title: 'Odstranění šlahounů', task_type: 'strihani', frequency_days: 14 },
      { title: 'Zimní ochrana jahod', task_type: 'jine', frequency_days: 365, notes: 'Přikrýt chvojím nebo fólií v listopadu' },
    ],
  },
  {
    id: 22,
    nameCz: 'Malina',
    nameLat: 'Rubus idaeus',
    soil: 'Humózní, propustná, mírně kyselá pH 6–6,5',
    sun: '☀️ Slunce, toleruje polostín',
    watering: '1–2× týdně',
    fertilizing: 'Kompost na jaře, hnojivo v červnu',
    pruning: 'Po sklizni odstraňovat dvouleté výhony (hnědé). Nové (zelené) nechat.',
    planting: 'Podzim nebo jaro, vázat k drátěnce',
    notes: 'Výhony fruktifikují ve druhém roce — ty staré po sklizni vykácej.',
    tasks: [
      { title: 'Zálivka maliny', task_type: 'zalivka', frequency_days: 5 },
      { title: 'Hnojení maliny', task_type: 'hnojeni', frequency_days: 30 },
      { title: 'Sklizeň maliny', task_type: 'sklizen', frequency_days: 3 },
      { title: 'Řez maliny (po sklizni)', task_type: 'strihani', frequency_days: 365, notes: 'Odřezat dvouleté hnědé výhony po sklizni' },
      { title: 'Jarní přivazování', task_type: 'jine', frequency_days: 365, notes: 'Přivázat nové výhony k drátěnce' },
    ],
  },
  {
    id: 23,
    nameCz: 'Borůvka',
    nameLat: 'Vaccinium corymbosum',
    soil: 'Výrazně kyselá, rašelinová, pH 4–5',
    sun: '☀️ Plné slunce',
    watering: 'Pravidelně, nesmí vyschnout. Dešťová nebo měkká voda.',
    fertilizing: 'Hnojivo pro borůvky (síranové) na jaře',
    pruning: 'Starší větve řezat v únoru–březnu každé 3–4 roky',
    planting: 'Jaro nebo podzim, sázet 2 různé odrůdy pro opylení',
    notes: 'Okyselovat půdu síranem amonným. Mulčovat borůvkovou kůrou.',
    tasks: [
      { title: 'Zálivka borůvek', task_type: 'zalivka', frequency_days: 4, notes: 'Dešťová nebo změkčená voda' },
      { title: 'Hnojení borůvek (kyselé)', task_type: 'hnojeni', frequency_days: 60, notes: 'Sírové hnojivo pro azalky a borůvky' },
      { title: 'Sklizeň borůvek', task_type: 'sklizen', frequency_days: 5 },
      { title: 'Jarní řez borůvek', task_type: 'strihani', frequency_days: 365, notes: 'Únor–březen: odřezat staré větve' },
    ],
  },
  {
    id: 24,
    nameCz: 'Rybíz červený',
    nameLat: 'Ribes rubrum',
    soil: 'Výživná, humózní',
    sun: '☀️ Slunce, toleruje polostín',
    watering: '1× týdně',
    fertilizing: 'Kompost na jaře',
    pruning: 'Zimní řez: odstraňovat větve starší 3–4 let',
    planting: 'Podzim, nebo jaro',
    notes: 'Keř nese plody na dvouletém a tříletém dřevě. Síť proti ptákům.',
    tasks: [
      { title: 'Zálivka rybízu', task_type: 'zalivka', frequency_days: 7 },
      { title: 'Sklizeň rybízu', task_type: 'sklizen', frequency_days: 5 },
      { title: 'Zimní řez rybízu', task_type: 'strihani', frequency_days: 365, notes: 'Prosinec–únor: odřezat větve starší 3 let' },
      { title: 'Jarní hnojení', task_type: 'hnojeni', frequency_days: 365 },
    ],
  },
  {
    id: 25,
    nameCz: 'Angrešt',
    nameLat: 'Ribes uva-crispa',
    soil: 'Propustná, humózní',
    sun: '⛅ Polostín i slunce',
    watering: '1× týdně',
    fertilizing: 'Kompost na jaře a podzim',
    pruning: 'Letní zkracování, zimní prosvětlení',
    planting: 'Podzim nebo jaro',
    notes: 'Náchylný na padlí americké — nenatěsnávat, dobré větrání.',
    tasks: [
      { title: 'Zálivka angreštu', task_type: 'zalivka', frequency_days: 7 },
      { title: 'Sklizeň angreštu', task_type: 'sklizen', frequency_days: 7 },
      { title: 'Letní zkracování', task_type: 'strihani', frequency_days: 365, notes: 'Červenec: zkrátit nové výhony na 5 listů' },
      { title: 'Kontrola padlí', task_type: 'kontrola', frequency_days: 10 },
    ],
  },
  {
    id: 26,
    nameCz: 'Ostružina',
    nameLat: 'Rubus fruticosus',
    soil: 'Humózní, propustná',
    sun: '☀️ Slunce',
    watering: '1–2× týdně',
    fertilizing: 'Kompost na jaře',
    pruning: 'Po sklizni odstranit dvouleté výhony, přivázat nové',
    planting: 'Jaro nebo podzim, potřebuje drátěnku',
    notes: 'Trny! Pracovat s rukavicemi. Plody sklízet zralé — tmavě černé.',
    tasks: [
      { title: 'Zálivka ostružin', task_type: 'zalivka', frequency_days: 5 },
      { title: 'Sklizeň ostružin', task_type: 'sklizen', frequency_days: 3 },
      { title: 'Řez ostružin', task_type: 'strihani', frequency_days: 365, notes: 'Po sklizni: odstranit staré výhony' },
    ],
  },

  // ==================== BYLINY ====================
  {
    id: 27,
    nameCz: 'Bazalka',
    nameLat: 'Ocimum basilicum',
    soil: 'Lehká, výživná, dobře zahřátá',
    sun: '☀️ Plné slunce, chráněné',
    watering: 'Pravidelně, ne přemokřit. Pokojová teplota vody.',
    fertilizing: 'Mírně každých 3–4 týdny',
    pruning: 'Pravidelně odstřihávat vršky pro větvení, odstraňovat květní stvoly',
    planting: 'Přesazovat po 15. května, nebo pěstovat na okně',
    notes: 'Nesnáší mráz ani průvan. Nekombinovat se šalvějí.',
    tasks: [
      { title: 'Zálivka bazalky', task_type: 'zalivka', frequency_days: 3, notes: 'Vlažná voda, neplnit talíř vodou' },
      { title: 'Zastřihávání bazalky', task_type: 'strihani', frequency_days: 10, notes: 'Odstraňovat pupeny pro větvení' },
      { title: 'Hnojení bazalky', task_type: 'hnojeni', frequency_days: 28 },
    ],
  },
  {
    id: 28,
    nameCz: 'Tymián',
    nameLat: 'Thymus vulgaris',
    soil: 'Suchá, propustná, chudá, alkalická',
    sun: '☀️ Plné slunce',
    watering: 'Střídmě — nesnáší přemokření',
    fertilizing: 'Jen výjimečně, chudá půda prospívá',
    pruning: 'Po odkvětu zkrátit o třetinu pro větvení',
    planting: 'Jaro, i na balkon nebo skalničkový záhon',
    notes: 'Vytrvalá bylina, mrazuvzdorná. Skvělá pro včely.',
    tasks: [
      { title: 'Zálivka tymiánu', task_type: 'zalivka', frequency_days: 7 },
      { title: 'Řez tymiánu (po odkvětu)', task_type: 'strihani', frequency_days: 365, notes: 'Zkrátit o třetinu po odkvětu' },
    ],
  },
  {
    id: 29,
    nameCz: 'Rozmarýn',
    nameLat: 'Salvia rosmarinus',
    soil: 'Suchá, propustná, vápenatá',
    sun: '☀️ Plné slunce',
    watering: 'Střídmě, přemokření vadí',
    fertilizing: 'Jen slabě na jaře',
    pruning: 'Po odkvětu zkrátit pro kompaktní tvar',
    planting: 'Jaro, chráněné místo. V zimě přinést dovnitř (nesnáší tuhé mrazy).',
    notes: 'Polotrvalá v chráněných polohách. Sušit výhony pro koření.',
    tasks: [
      { title: 'Zálivka rozmarýnu', task_type: 'zalivka', frequency_days: 7 },
      { title: 'Přesun rozmarýnu na zimu', task_type: 'presazeni', frequency_days: 365, notes: 'Říjen: přenést do světlé místnosti nad 5 °C' },
      { title: 'Jarní řez rozmarýnu', task_type: 'strihani', frequency_days: 365 },
    ],
  },
  {
    id: 30,
    nameCz: 'Máta peprná',
    nameLat: 'Mentha × piperita',
    soil: 'Vlhká, humózní',
    sun: '⛅ Polostín i slunce',
    watering: 'Hojně, nesmí vyschnout',
    fertilizing: 'Kompost každé jaro',
    pruning: 'Pravidelně sekat pro větvení, odstraňovat odkvětlé části',
    planting: 'Jaro, ideálně do nádoby (invazivní!)',
    notes: 'Sázet do nádoby nebo ohraničit — máta se šíří oddenky a zaplevelí záhon.',
    tasks: [
      { title: 'Zálivka máty', task_type: 'zalivka', frequency_days: 3 },
      { title: 'Seč máty', task_type: 'strihani', frequency_days: 21, notes: 'Sekat pro větvení a pro sběr' },
    ],
  },
  {
    id: 31,
    nameCz: 'Šalvěj lékařská',
    nameLat: 'Salvia officinalis',
    soil: 'Propustná, vápenatá, suchá',
    sun: '☀️ Plné slunce',
    watering: 'Střídmě',
    fertilizing: 'Minimálně',
    pruning: 'Zkrátit po odkvětu pro kompaktní tvar',
    planting: 'Jaro, slunné a suché místo',
    notes: 'Vytrvalá, mrazuvzdorná. Řezat čerstvé lístky pro vaření.',
    tasks: [
      { title: 'Zálivka šalvěje', task_type: 'zalivka', frequency_days: 7 },
      { title: 'Řez šalvěje', task_type: 'strihani', frequency_days: 365, notes: 'Po odkvětu zkrátit o třetinu' },
    ],
  },
  {
    id: 32,
    nameCz: 'Pažitka',
    nameLat: 'Allium schoenoprasum',
    soil: 'Humózní, středně výživná',
    sun: '☀️ Slunce i polostín',
    watering: 'Pravidelně mírně',
    fertilizing: 'Dusíkaté hnojivo na jaře',
    pruning: 'Sekat pravidelně u kořene pro nový růst, odstraňovat fialové květy',
    planting: 'Jaro nebo podzim, přes zimu dormantní',
    notes: 'Velmi nenáročná vytrvalá bylina. Rozmnožuje se dělením trsů.',
    tasks: [
      { title: 'Zálivka pažitky', task_type: 'zalivka', frequency_days: 5 },
      { title: 'Seč pažitky', task_type: 'strihani', frequency_days: 21 },
      { title: 'Dělení pažitky', task_type: 'presazeni', frequency_days: 365, notes: 'Na jaře rozdělit přerostlý trs' },
    ],
  },
  {
    id: 33,
    nameCz: 'Oregano',
    nameLat: 'Origanum vulgare',
    soil: 'Propustná, suchá, chudá',
    sun: '☀️ Plné slunce',
    watering: 'Střídmě, sucho prospívá',
    fertilizing: 'Minimálně',
    pruning: 'Sekat před kvetením pro nejlepší chuť',
    planting: 'Jaro, slunné místo',
    notes: 'Výborná pro včely. Sušit na závěs.',
    tasks: [
      { title: 'Zálivka oregana', task_type: 'zalivka', frequency_days: 7 },
      { title: 'Seč oregana', task_type: 'strihani', frequency_days: 30 },
    ],
  },
  {
    id: 34,
    nameCz: 'Meduňka lékařská',
    nameLat: 'Melissa officinalis',
    soil: 'Humózní, propustná',
    sun: '⛅ Polostín',
    watering: 'Pravidelně, nesmí vyschnout',
    fertilizing: 'Kompost na jaře',
    pruning: 'Pravidelně sekat, odstraňovat odkvětlé části pro větvení',
    planting: 'Jaro, může být invazivní — vhodná i do nádoby',
    notes: 'Uklidňující bylina. Velmi odolná a nenáročná.',
    tasks: [
      { title: 'Zálivka meduňky', task_type: 'zalivka', frequency_days: 4 },
      { title: 'Seč meduňky', task_type: 'strihani', frequency_days: 21 },
    ],
  },
  {
    id: 35,
    nameCz: 'Levandule',
    nameLat: 'Lavandula angustifolia',
    soil: 'Propustná, suchá, alkalická',
    sun: '☀️ Plné slunce',
    watering: 'Střídmě, po zaschnutí',
    fertilizing: 'Minimálně — chudá půda',
    pruning: 'Po odkvětu zkrátit zelené výhony o třetinu, ne do starého dřeva',
    planting: 'Jaro nebo podzim na výslunné suché místo',
    notes: 'Výborná pro včely a motýly. Sušit pro vůni i do polštářků.',
    tasks: [
      { title: 'Zálivka levandule', task_type: 'zalivka', frequency_days: 10 },
      { title: 'Řez levandule (po odkvětu)', task_type: 'strihani', frequency_days: 365, notes: 'Srpen: zkrátit o třetinu zelené výhony' },
    ],
  },
  {
    id: 36,
    nameCz: 'Koriandr',
    nameLat: 'Coriandrum sativum',
    soil: 'Propustná, středně výživná',
    sun: '☀️ Slunce, lehký stín v létě',
    watering: 'Pravidelně, rovnoměrně',
    fertilizing: 'Málo',
    pruning: 'Sekat horní lístky',
    planting: 'Přímo sít od dubna, po 3 týdnech opakovat pro nepřetržitou sklizeň',
    notes: 'Rychle vykvétá v horku. Opakovat výsev každé 3 týdny.',
    tasks: [
      { title: 'Zálivka koriandru', task_type: 'zalivka', frequency_days: 3 },
      { title: 'Sklizeň koriandru', task_type: 'sklizen', frequency_days: 7 },
    ],
  },
  {
    id: 37,
    nameCz: 'Estragon francouzský',
    nameLat: 'Artemisia dracunculus',
    soil: 'Propustná, suchá',
    sun: '☀️ Plné slunce',
    watering: 'Střídmě',
    fertilizing: 'Minimálně',
    pruning: 'Před kvetením sekat pro nejlepší aroma',
    planting: 'Jaro, pouze přesazením (semena nezralá)',
    notes: 'Pouze francouzský estragon (ne ruský) má intenzivní chuť.',
    tasks: [
      { title: 'Zálivka estragonu', task_type: 'zalivka', frequency_days: 7 },
      { title: 'Seč estragonu', task_type: 'strihani', frequency_days: 30 },
    ],
  },
  {
    id: 38,
    nameCz: 'Heřmánek pravý',
    nameLat: 'Matricaria chamomilla',
    soil: 'Chudá, suchá, propustná',
    sun: '☀️ Plné slunce',
    watering: 'Minimálně po zaschnutí',
    fertilizing: 'Vůbec — čím chudší půda, tím lépe',
    pruning: 'Sbírat otevřené kvety pro sušení',
    planting: 'Březen–duben přímo sít, samosev v dalších letech',
    notes: 'Jednoletá, ale bohatě samoseje. Sbírat v ranních hodinách.',
    tasks: [
      { title: 'Zálivka heřmánku', task_type: 'zalivka', frequency_days: 7 },
      { title: 'Sklizeň heřmánku', task_type: 'sklizen', frequency_days: 5, notes: 'Sbírat čerstvě otevřené kvety' },
    ],
  },
  {
    id: 39,
    nameCz: 'Třezalka tečkovaná',
    nameLat: 'Hypericum perforatum',
    soil: 'Suchá, propustná',
    sun: '☀️ Plné slunce',
    watering: 'Minimálně',
    fertilizing: 'Vůbec',
    pruning: 'Sekat po odkvětu pro větvení',
    planting: 'Jaro nebo podzim',
    notes: 'Léčivá bylina. Sbírat kvetoucí vrcholky v červnu–červenci.',
    tasks: [
      { title: 'Zálivka třezalky', task_type: 'zalivka', frequency_days: 10 },
      { title: 'Sklizeň třezalky', task_type: 'sklizen', frequency_days: 14 },
    ],
  },

  // ==================== OKRASNÉ KVETOUCÍ ====================
  {
    id: 40,
    nameCz: 'Růže zahradní',
    nameLat: 'Rosa',
    soil: 'Hlinitopísčitá, bohatá na humus, pH 6–6,5',
    sun: '☀️ Plné slunce (min. 6 h)',
    watering: '2× týdně u kořene, ne na listy',
    fertilizing: 'Od dubna do července každých 14 dní',
    pruning: 'Jarní řez v březnu (na 3–5 oček), deadheading v průběhu léta',
    planting: 'Jaro nebo podzim',
    notes: 'Kontrolovat mšice, padlí, černou skvrnitost. Preventivně postřikovat.',
    tasks: [
      { title: 'Zálivka růží', task_type: 'zalivka', frequency_days: 3, notes: 'U kořene, ne na listy' },
      { title: 'Hnojení růží', task_type: 'hnojeni', frequency_days: 14, notes: 'Speciální hnojivo pro růže' },
      { title: 'Deadheading růží', task_type: 'strihani', frequency_days: 7, notes: 'Odstraňovat odkvetlé květy' },
      { title: 'Kontrola mšic a padlí', task_type: 'kontrola', frequency_days: 7 },
      { title: 'Jarní řez růží', task_type: 'strihani', frequency_days: 365, notes: 'Březen: řez na 3–5 oček nad zemí' },
    ],
  },
  {
    id: 41,
    nameCz: 'Hortenzie',
    nameLat: 'Hydrangea',
    soil: 'Kyselejší, humózní, vlhká, pH 5–6,5',
    sun: '⛅ Polostín (přímé poledne škodí)',
    watering: 'Hojně 2–3× týdně, vodu nemiluje tvrdou',
    fertilizing: 'Na jaře a v červnu hnojivem pro azalky',
    pruning: 'Jarní řez: odstraňovat suché odkvětlé panicle, nést jen slabé větve',
    planting: 'Jaro nebo podzim, chráněné místo',
    notes: 'Barva závisí na pH: kyselá = modrá, zásaditá = růžová. Okyselovat síranem hlinitým.',
    tasks: [
      { title: 'Zálivka hortenzie', task_type: 'zalivka', frequency_days: 3, notes: 'Hojně, ideálně dešťová voda' },
      { title: 'Hnojení hortenzie', task_type: 'hnojeni', frequency_days: 30, notes: 'Hnojivo pro azalky (kyselé)' },
      { title: 'Jarní řez hortenzie', task_type: 'strihani', frequency_days: 365, notes: 'Březne: odstraňovat suché odkvětlé panicle' },
      { title: 'Zimní ochrana hortenzie', task_type: 'jine', frequency_days: 365, notes: 'Říjen: přikrýt kořenový krček mulčem' },
    ],
  },
  {
    id: 42,
    nameCz: 'Šeřík',
    nameLat: 'Syringa vulgaris',
    soil: 'Propustná, mírně zásaditá, pH 6,5–7,5',
    sun: '☀️ Plné slunce',
    watering: 'Střídmě po zaschnutí, odolný suchu',
    fertilizing: 'Kompost na jaře, draselné hnojivo v létě',
    pruning: 'Hned po odkvětu, odstraňovat odkvetlé kytice',
    planting: 'Podzim nebo jaro',
    notes: 'Neřezat příliš brzy — kvete na loňském dřevě. Řezat těsně po odkvětu.',
    tasks: [
      { title: 'Zálivka šeříku', task_type: 'zalivka', frequency_days: 7 },
      { title: 'Řez šeříku (po odkvětu)', task_type: 'strihani', frequency_days: 365, notes: 'Ihned po odkvětu odstranit odkvetlé hrozny' },
      { title: 'Hnojení šeříku', task_type: 'hnojeni', frequency_days: 365, notes: 'Kompost na jaře' },
    ],
  },
  {
    id: 43,
    nameCz: 'Fuchsie',
    nameLat: 'Fuchsia',
    soil: 'Výživná, propustná substrát pro trvalky',
    sun: '⛅ Polostín, ne přímé polední slunce',
    watering: 'Hojně v létě, 1–2× denně v parnu',
    fertilizing: 'Každých 7–10 dní tekutým hnojivem v létě',
    pruning: 'Na jaře zkrátit o třetinu pro větvení',
    planting: 'Po 15. května, ideálně do závěsných košů',
    notes: 'Nesnáší mráz. Přezimovat v chladu (5–10 °C) a suchu.',
    tasks: [
      { title: 'Zálivka fuchsie', task_type: 'zalivka', frequency_days: 2 },
      { title: 'Hnojení fuchsie', task_type: 'hnojeni', frequency_days: 10, notes: 'Tekuté hnojivo na kvetoucí rostliny' },
      { title: 'Přezimování fuchsie', task_type: 'presazeni', frequency_days: 365, notes: 'Říjen: přenést do chladu 5–10 °C, omezit zálivku' },
      { title: 'Jarní řez fuchsie', task_type: 'strihani', frequency_days: 365, notes: 'Únor: zkrátit o třetinu' },
    ],
  },
  {
    id: 44,
    nameCz: 'Pelargónie (Muškát)',
    nameLat: 'Pelargonium',
    soil: 'Propustná, středně výživná',
    sun: '☀️ Slunce, toleruje i polostín',
    watering: 'Pravidelně po zaschnutí, ne přemokřit',
    fertilizing: 'Každých 7–14 dní hnojivem pro kvetoucí',
    pruning: 'Deadheading, na jaře zkrátit o třetinu',
    planting: 'Po 15. května ven',
    notes: 'Přezimovat v chladu a světle. Pravidelně deadheadovat pro nepřetržité kvetení.',
    tasks: [
      { title: 'Zálivka pelargónie', task_type: 'zalivka', frequency_days: 3 },
      { title: 'Hnojení pelargónie', task_type: 'hnojeni', frequency_days: 10 },
      { title: 'Deadheading pelargónie', task_type: 'strihani', frequency_days: 7 },
      { title: 'Přezimování pelargónie', task_type: 'presazeni', frequency_days: 365, notes: 'Říjen: přenést do světlé místnosti, 10–15 °C' },
    ],
  },
  {
    id: 45,
    nameCz: 'Begónie hlíznatá',
    nameLat: 'Begonia × tuberhybrida',
    soil: 'Lehká, propustná, humózní',
    sun: '⛅ Polostín, ne přímé slunce',
    watering: 'Pravidelně, ne na květy',
    fertilizing: 'Každých 10–14 dní hnojivem pro kvetoucí',
    pruning: 'Deadheading pro nepřetržité kvetení',
    planting: 'Hlízy zasadit v březnu do substrátu, ven po 15. května',
    notes: 'Na podzim vykopat hlízy, osušit a uskladnit nad 5 °C.',
    tasks: [
      { title: 'Zálivka begónie', task_type: 'zalivka', frequency_days: 3 },
      { title: 'Hnojení begónie', task_type: 'hnojeni', frequency_days: 12 },
      { title: 'Vykopání hlíz begónie', task_type: 'jine', frequency_days: 365, notes: 'Říjen: před mrazem vykopat a usušit hlízy' },
    ],
  },
  {
    id: 46,
    nameCz: 'Dahlia (Jiřina)',
    nameLat: 'Dahlia',
    soil: 'Výživná, humózní, propustná',
    sun: '☀️ Plné slunce',
    watering: '2–3× týdně hojně',
    fertilizing: 'Každých 14 dní hnojivem s draslíkem od července',
    pruning: 'Pinzovat první výhony pro větvení. Deadheadovat pravidelně.',
    planting: 'Hlízy sázet v květnu po mrazech',
    notes: 'Vykopat po prvním mrazu, přezimovat v suchém prostoru nad 5 °C.',
    tasks: [
      { title: 'Zálivka dahlie', task_type: 'zalivka', frequency_days: 3 },
      { title: 'Hnojení dahlie', task_type: 'hnojeni', frequency_days: 14 },
      { title: 'Deadheading dahlie', task_type: 'strihani', frequency_days: 7 },
      { title: 'Vykopání hlíz dahlie', task_type: 'jine', frequency_days: 365, notes: 'Po prvním mrazu — vykopat, osušit, uskladnit v suchém prostoru' },
    ],
  },
  {
    id: 47,
    nameCz: 'Slunečnice',
    nameLat: 'Helianthus annuus',
    soil: 'Výživná, propustná',
    sun: '☀️ Plné slunce',
    watering: '1–2× týdně, odolná suchu',
    fertilizing: 'Dusíkaté hnojivo v červnu',
    pruning: 'Zástupné odrůdy: pinzovat pro více hlav',
    planting: 'Duben–květen přímo sít nebo přesazovat po mrazech',
    notes: 'Vázat vysoké odrůdy. Semena sklízet na sušení v záři.',
    tasks: [
      { title: 'Zálivka slunečnice', task_type: 'zalivka', frequency_days: 5 },
      { title: 'Hnojení slunečnice', task_type: 'hnojeni', frequency_days: 21 },
      { title: 'Sklizeň semen slunečnice', task_type: 'sklizen', frequency_days: 365, notes: 'Září: sklízet zralé hlávky po zaschnutí' },
    ],
  },
  {
    id: 48,
    nameCz: 'Chrpa zahradní',
    nameLat: 'Centaurea cyanus',
    soil: 'Chudá, propustná',
    sun: '☀️ Plné slunce',
    watering: 'Mírně, toleruje sucho',
    fertilizing: 'Není potřeba',
    pruning: 'Deadheadovat pro prodloužení kvetení',
    planting: 'Přímý výsev duben, nebo samosev',
    notes: 'Jednoletá, ale bohatě samoseje. Výborná pro opylovatele.',
    tasks: [
      { title: 'Zálivka chrpy', task_type: 'zalivka', frequency_days: 7 },
      { title: 'Deadheading chrpy', task_type: 'strihani', frequency_days: 10 },
    ],
  },
  {
    id: 49,
    nameCz: 'Měsíček lékařský',
    nameLat: 'Calendula officinalis',
    soil: 'Propustná, průměrná',
    sun: '☀️ Slunce',
    watering: 'Mírně',
    fertilizing: 'Málo',
    pruning: 'Deadheadovat intenzivně pro dlouhé kvetení',
    planting: 'Duben–květen přímo sít',
    notes: 'Léčivý. Odpuzuje škůdce v záhoně. Sbírat pevně uzavřené kvety pro mast.',
    tasks: [
      { title: 'Zálivka měsíčku', task_type: 'zalivka', frequency_days: 5 },
      { title: 'Deadheading měsíčku', task_type: 'strihani', frequency_days: 7 },
      { title: 'Sklizeň měsíčku', task_type: 'sklizen', frequency_days: 7, notes: 'Sbírat uzavřené nebo čerstvě otevřené kvety' },
    ],
  },
  {
    id: 50,
    nameCz: 'Petúnie',
    nameLat: 'Petunia',
    soil: 'Propustná, středně výživná',
    sun: '☀️ Plné slunce',
    watering: '1× denně v parnu (zvláště v závěsných košech)',
    fertilizing: 'Každých 7–10 dní tekutým hnojivem',
    pruning: 'Každé 3–4 týdny zastřihnout pro větvení, deadheadovat',
    planting: 'Po 15. května ven',
    notes: 'Nádobové i záhonové odrůdy. Pravidelné hnojení klíčové pro kvetení.',
    tasks: [
      { title: 'Zálivka petúnií', task_type: 'zalivka', frequency_days: 2 },
      { title: 'Hnojení petúnií', task_type: 'hnojeni', frequency_days: 10 },
      { title: 'Zastřihávání petúnií', task_type: 'strihani', frequency_days: 21 },
    ],
  },
  {
    id: 51,
    nameCz: 'Lobelka',
    nameLat: 'Lobelia erinus',
    soil: 'Propustná, humózní',
    sun: '⛅ Polostín, toleruje slunce',
    watering: 'Pravidelně, nesmí vyschnout',
    fertilizing: 'Každých 14 dní',
    pruning: 'Nastřihnout po první vlně kvetení pro obnovu',
    planting: 'Po 15. května',
    notes: 'Skvělá do závěsných košů a lemování záhonů.',
    tasks: [
      { title: 'Zálivka lobelky', task_type: 'zalivka', frequency_days: 2 },
      { title: 'Hnojení lobelky', task_type: 'hnojeni', frequency_days: 14 },
      { title: 'Zastřihávání lobelky', task_type: 'strihani', frequency_days: 30, notes: 'Po první vlně kvetení nastřihnout o třetinu' },
    ],
  },

  // ==================== CIBULOVINY ====================
  {
    id: 52,
    nameCz: 'Tulipán',
    nameLat: 'Tulipa',
    soil: 'Propustná, neutrální',
    sun: '☀️ Plné slunce',
    watering: 'Jen při výsadbě a na jaře pokud sucho',
    fertilizing: 'Speciální cibulové hnojivo při výsadbě',
    pruning: 'Po odkvětu nechat listy zežloutnout a uschnout přirozeně',
    planting: 'Říjen–listopad do hloubky 15 cm',
    notes: 'Nespěchat se sezonováním listů — zásobí cibulku na příští rok.',
    tasks: [
      { title: 'Výsadba tulipánů', task_type: 'jine', frequency_days: 365, notes: 'Říjen–listopad: sázet do hloubky 15 cm' },
      { title: 'Zálivka tulipánů', task_type: 'zalivka', frequency_days: 14, notes: 'Jen v suchu na jaře' },
      { title: 'Odebrání odkvětlých stonků', task_type: 'strihani', frequency_days: 365, notes: 'Odříznout stonek po odkvětu, listy nechat' },
    ],
  },
  {
    id: 53,
    nameCz: 'Narcis',
    nameLat: 'Narcissus',
    soil: 'Propustná, humózní',
    sun: '☀️ Slunce i polostín',
    watering: 'Jen při výsadbě',
    fertilizing: 'Cibulové hnojivo při výsadbě',
    pruning: 'Po odkvětu nechat listy přirozeně uschnout',
    planting: 'Září–říjen, hloubka 10–15 cm',
    notes: 'Toxický pro hlodavce — přirozená ochrana. Naturalizuje se a množí.',
    tasks: [
      { title: 'Výsadba narcisů', task_type: 'jine', frequency_days: 365, notes: 'Září–říjen: hloubka 10–15 cm' },
      { title: 'Deadheading narcisů', task_type: 'strihani', frequency_days: 365, notes: 'Odříznout odkvetlý stonek, listy nechat' },
    ],
  },
  {
    id: 54,
    nameCz: 'Hyacint',
    nameLat: 'Hyacinthus orientalis',
    soil: 'Propustná, humózní',
    sun: '☀️ Plné slunce',
    watering: 'Mírně na jaře',
    fertilizing: 'Cibulové hnojivo při výsadbě',
    pruning: 'Po odkvětu nechat listy zežloutnout',
    planting: 'Říjen–listopad, hloubka 10 cm',
    notes: 'Silná vůně. Citlivá kůže — rukavice při manipulaci.',
    tasks: [
      { title: 'Výsadba hyacintů', task_type: 'jine', frequency_days: 365, notes: 'Říjen–listopad: hloubka 10 cm' },
      { title: 'Deadheading hyacintů', task_type: 'strihani', frequency_days: 365 },
    ],
  },
  {
    id: 55,
    nameCz: 'Gladiola',
    nameLat: 'Gladiolus',
    soil: 'Propustná, výživná',
    sun: '☀️ Plné slunce',
    watering: '1× týdně hojně',
    fertilizing: 'Draselné hnojivo v červnu',
    pruning: 'Po odkvětu odříznout stonek, nechat listy',
    planting: 'Duben–května, hloubka 10–15 cm. Opakovaně po 2 týdnech pro prodloužení kvetení.',
    notes: 'Vykopat na podzim před mrazem, přezimovat v suchém prostoru.',
    tasks: [
      { title: 'Zálivka gladiol', task_type: 'zalivka', frequency_days: 7 },
      { title: 'Hnojení gladiol', task_type: 'hnojeni', frequency_days: 30 },
      { title: 'Vykopání hlíz gladiol', task_type: 'jine', frequency_days: 365, notes: 'Říjen: vykopat, osušit, uskladnit v suchém 5–10 °C' },
    ],
  },
  {
    id: 56,
    nameCz: 'Lilie',
    nameLat: 'Lilium',
    soil: 'Výživná, humózní, propustná',
    sun: '☀️ Slunce, ale kořen v chladnu (mulčovat)',
    watering: '1–2× týdně, ne na listy',
    fertilizing: 'Draselné hnojivo při rašení a před kvetením',
    pruning: 'Po odkvětu odříznout stonek, listy nechat do podzimu',
    planting: 'Podzim nebo jaro, hloubka 15–20 cm',
    notes: 'POZOR: jedovaté pro kočky! Červení brouci: sbírat ručně.',
    tasks: [
      { title: 'Zálivka lilií', task_type: 'zalivka', frequency_days: 5 },
      { title: 'Hnojení lilií', task_type: 'hnojeni', frequency_days: 30 },
      { title: 'Kontrola červených brouků', task_type: 'kontrola', frequency_days: 7, notes: 'Rycale: sbírat broučky ručně nebo postříkat' },
    ],
  },
  {
    id: 57,
    nameCz: 'Krokus',
    nameLat: 'Crocus',
    soil: 'Propustná, suchá',
    sun: '☀️ Slunce',
    watering: 'Není potřeba',
    fertilizing: 'Minimálně',
    pruning: 'Po odkvětu nechat listy uschnout',
    planting: 'Září–říjen, hloubka 5–8 cm',
    notes: 'Jeden z prvních jarních cibulovin. Naturalizuje se. Oblíbené pro včely.',
    tasks: [
      { title: 'Výsadba krokusů', task_type: 'jine', frequency_days: 365, notes: 'Září–říjen: hloubka 5–8 cm' },
    ],
  },

  // ==================== KEŘE A STROMY ====================
  {
    id: 58,
    nameCz: 'Buxus (zimostráz)',
    nameLat: 'Buxus sempervirens',
    soil: 'Vápnatá, propustná, humózní',
    sun: '⛅ Polostín až slunce',
    watering: '1× týdně v suchu',
    fertilizing: 'Dusíkaté hnojivo na jaře, vápenec pokud kyselá půda',
    pruning: 'Tvarovat 2× ročně: červen a srpen',
    planting: 'Jaro nebo podzim',
    notes: 'Náchylný na buxusovou housenku — kontrolovat pravidelně a postřikovat.',
    tasks: [
      { title: 'Zálivka buxusu', task_type: 'zalivka', frequency_days: 7 },
      { title: 'Tvarování buxusu', task_type: 'strihani', frequency_days: 180, notes: 'Červen a srpen: stříhat do tvaru' },
      { title: 'Kontrola housenky buxusové', task_type: 'kontrola', frequency_days: 14, notes: 'Hledat housenky nebo přediví na větvích' },
    ],
  },
  {
    id: 59,
    nameCz: 'Pěnišník (Rododendron)',
    nameLat: 'Rhododendron',
    soil: 'Rašelinová, kyselá, pH 4,5–5,5, propustná',
    sun: '⛅ Polostín (přímé poledne škodí)',
    watering: 'Hojně, dešťová nebo měkčená voda',
    fertilizing: 'Kyselé hnojivo (pro azalky/rododendrony) na jaře',
    pruning: 'Ihned po odkvětu odštípnout odkvetlé hrozny',
    planting: 'Jaro nebo podzim, chráněné od větru',
    notes: 'Nesnáší vápenatou vodu ani sucho. Mulčovat rašelinou.',
    tasks: [
      { title: 'Zálivka rododendrónu', task_type: 'zalivka', frequency_days: 5, notes: 'Dešťová nebo změkčená voda' },
      { title: 'Hnojení rododendrónu', task_type: 'hnojeni', frequency_days: 30, notes: 'Kyselé hnojivo pro azalky' },
      { title: 'Deadheading rododendrónu', task_type: 'strihani', frequency_days: 365, notes: 'Ihned po odkvětu odštípnout odkvetlé hrozny' },
    ],
  },
  {
    id: 60,
    nameCz: 'Tavolník',
    nameLat: 'Spiraea',
    soil: 'Propustná, průměrná',
    sun: '☀️ Slunce, toleruje polostín',
    watering: 'Odolný suchu, v prvním roce zaléhat',
    fertilizing: 'Kompost na jaře',
    pruning: 'Po odkvětu zkrátit (jarní druhy), nebo koncem zimy (letní druhy)',
    planting: 'Jaro nebo podzim',
    notes: 'Velmi nenáročný. Druhy se liší dobou kvetení — jarní vs. letní.',
    tasks: [
      { title: 'Zálivka tavolníku', task_type: 'zalivka', frequency_days: 10 },
      { title: 'Řez tavolníku', task_type: 'strihani', frequency_days: 365, notes: 'Jarní: po odkvětu. Letní (japonský): únor–březen' },
    ],
  },
  {
    id: 61,
    nameCz: 'Zimolez (Weigelie)',
    nameLat: 'Weigela',
    soil: 'Propustná, humózní',
    sun: '☀️ Slunce',
    watering: '1× týdně v suchu',
    fertilizing: 'Kompost na jaře',
    pruning: 'Po odkvětu prosvětlit, odstraňovat staré větve',
    planting: 'Jaro nebo podzim',
    notes: 'Kvete na loňském dřevě — neřezat příliš radikálně.',
    tasks: [
      { title: 'Zálivka weigélie', task_type: 'zalivka', frequency_days: 7 },
      { title: 'Řez weigélie (po odkvětu)', task_type: 'strihani', frequency_days: 365 },
    ],
  },
  {
    id: 62,
    nameCz: 'Dřišťál',
    nameLat: 'Berberis',
    soil: 'Propustná, průměrná',
    sun: '☀️ Slunce, toleruje polostín',
    watering: 'Odolný suchu',
    fertilizing: 'Minimálně',
    pruning: 'Prosvětlení na jaře, tvarování po odkvětu',
    planting: 'Jaro nebo podzim',
    notes: 'Trny — pracovat s rukavicemi. Atraktivní pro ptáky (plody).',
    tasks: [
      { title: 'Zálivka dřišťálu', task_type: 'zalivka', frequency_days: 14 },
      { title: 'Jarní řez dřišťálu', task_type: 'strihani', frequency_days: 365, notes: 'Prosvětlit, odstraňovat staré větve (rukavice!)' },
    ],
  },
  {
    id: 63,
    nameCz: 'Líska obecná',
    nameLat: 'Corylus avellana',
    soil: 'Humózní, propustná, pH 6–7',
    sun: '☀️ Slunce i polostín',
    watering: 'Odolná suchu v pozdějším věku',
    fertilizing: 'Kompost každé jaro',
    pruning: 'Po sklizni odstraňovat staré větve pro prosvětlení',
    planting: 'Podzim nebo jaro',
    notes: 'Sázet min. 2 různé odrůdy pro opylení. Sklízet v srpnu–září.',
    tasks: [
      { title: 'Zálivka lísky', task_type: 'zalivka', frequency_days: 14 },
      { title: 'Sklizeň lískových ořechů', task_type: 'sklizen', frequency_days: 365, notes: 'Srpen–září: sklízet opadávající ořechy' },
      { title: 'Zimní řez lísky', task_type: 'strihani', frequency_days: 365, notes: 'Leden–únor: prosvětlit, odstranit staré větve' },
    ],
  },
  {
    id: 64,
    nameCz: 'Oleandr',
    nameLat: 'Nerium oleander',
    soil: 'Propustná, středně výživná',
    sun: '☀️ Plné slunce',
    watering: 'Hojně v létě, minimálně v zimě',
    fertilizing: 'Každých 14 dní v létě hnojivem pro kvetoucí',
    pruning: 'Po odkvětu zkrátit pro větvení',
    planting: 'Nádoba — přenést ven po 15. května',
    notes: 'JEDOVATÝ — všechny části! Nejíst, nemýt nádobí v kalníku. Přezimovat v světlé místnosti 5–10 °C.',
    tasks: [
      { title: 'Zálivka oleandru', task_type: 'zalivka', frequency_days: 3, notes: 'V létě hojně, v zimě minimálně' },
      { title: 'Hnojení oleandru', task_type: 'hnojeni', frequency_days: 14 },
      { title: 'Přezimování oleandru', task_type: 'presazeni', frequency_days: 365, notes: 'Říjen: přenést do světlé místnosti 5–10 °C, skoro nezalévat' },
      { title: 'Kontrola mšic a červce', task_type: 'kontrola', frequency_days: 14 },
    ],
  },
  {
    id: 65,
    nameCz: 'Magnólie',
    nameLat: 'Magnolia',
    soil: 'Kyselá, humózní, propustná, pH 5–6,5',
    sun: '☀️ Slunce, chráněná od mrazivého větru',
    watering: '1× týdně v suchu, zejména mladé stromy',
    fertilizing: 'Kyselé hnojivo na jaře',
    pruning: 'Minimálně — jen po odkvětu, odstraňovat suché větve',
    planting: 'Jaro, chráněné místo',
    notes: 'Pomalu rostoucí, ale dožívá stovky let. Neřezat bez nutnosti.',
    tasks: [
      { title: 'Zálivka magnólie', task_type: 'zalivka', frequency_days: 7 },
      { title: 'Hnojení magnólie', task_type: 'hnojeni', frequency_days: 365, notes: 'Kyselé hnojivo na jaře (jednou ročně)' },
    ],
  },
  {
    id: 66,
    nameCz: 'Bambus zahradní',
    nameLat: 'Phyllostachys / Fargesia',
    soil: 'Humózní, propustná, středně výživná',
    sun: '⛅ Polostín i slunce',
    watering: 'Hojně zejména v prvních 2 letech, pak odolný',
    fertilizing: 'Dusíkaté hnojivo na jaře',
    pruning: 'Odstraňovat staré odumřelé kulmy (stonky)',
    planting: 'Jaro, ideálně s kořenovou bariérou (invazivní Phyllostachys!)',
    notes: 'Fargesia = trsnatý, nekorzivní. Phyllostachys = invazivní, vždy s bariérou!',
    tasks: [
      { title: 'Zálivka bambusu', task_type: 'zalivka', frequency_days: 5 },
      { title: 'Hnojení bambusu', task_type: 'hnojeni', frequency_days: 60, notes: 'Dusíkaté hnojivo na jaře' },
      { title: 'Řez starých kulm', task_type: 'strihani', frequency_days: 365, notes: 'Na jaře odstranit hnědé odumřelé stonky u kořene' },
    ],
  },
  {
    id: 67,
    nameCz: 'Wisterie (Vistárie)',
    nameLat: 'Wisteria',
    soil: 'Výživná, propustná, vlhká',
    sun: '☀️ Plné slunce',
    watering: 'Hojně v létě',
    fertilizing: 'Minimálně dusíku — jinak samé listy, bez květů. Draselné hnojivo.',
    pruning: '2× ročně: po odkvětu v létě zkrátit nové výhony na 5 oček; v zimě na 2–3 oka',
    planting: 'Jaro, pevná drátěnka nebo pergola. Rostlina těžká!',
    notes: 'Kvete až po 3–5 letech. Pohon kvetení: sucho a draslík, ne dusík!',
    tasks: [
      { title: 'Zálivka wisterie', task_type: 'zalivka', frequency_days: 5 },
      { title: 'Letní řez wisterie', task_type: 'strihani', frequency_days: 365, notes: 'Červenec–srpen: nové výhony zkrátit na 5 listů' },
      { title: 'Zimní řez wisterie', task_type: 'strihani', frequency_days: 365, notes: 'Leden–únor: zkrátit výhony na 2–3 oka' },
    ],
  },
  {
    id: 68,
    nameCz: 'Hortenzie latnatá (Vanilla Fraise)',
    nameLat: 'Hydrangea paniculata',
    soil: 'Výživná, propustná',
    sun: '☀️ Slunce i polostín',
    watering: '2× týdně',
    fertilizing: 'Na jaře hnojivem pro kvetoucí dřeviny',
    pruning: 'Konec února–březen: zkrátit výhony na 2–3 oka nad zemí',
    planting: 'Jaro nebo podzim',
    notes: 'Nejlehčeji pěstovatelná hortenzie. Toleruje vápenatou vodu.',
    tasks: [
      { title: 'Zálivka hortenzie latnaté', task_type: 'zalivka', frequency_days: 4 },
      { title: 'Hnojení hortenzie latnaté', task_type: 'hnojeni', frequency_days: 365, notes: 'Na jaře jednou hnojivem pro kvetoucí dřeviny' },
      { title: 'Zimní řez hortenzie latnaté', task_type: 'strihani', frequency_days: 365, notes: 'Únor–březen: zkrátit výhony na 2–3 oka' },
    ],
  },
  {
    id: 69,
    nameCz: 'Bergénie (Skalník)',
    nameLat: 'Bergenia',
    soil: 'Průměrná, humózní',
    sun: '⛅ Polostín i stín',
    watering: 'Střídmě, odolná suchu',
    fertilizing: 'Kompost na jaře',
    pruning: 'Na jaře odstraňovat suché zimní listy',
    planting: 'Jaro nebo podzim, nenáročná',
    notes: 'Stálezelená trvalka. Listy fialové v zimě. Vhodná pod stromy.',
    tasks: [
      { title: 'Zálivka bergénie', task_type: 'zalivka', frequency_days: 10 },
      { title: 'Jarní úklid bergénie', task_type: 'strihani', frequency_days: 365, notes: 'Odříznout poničené zimní listy' },
    ],
  },
  {
    id: 70,
    nameCz: 'Kontryhel (Alchemilla)',
    nameLat: 'Alchemilla mollis',
    soil: 'Humózní, propustná, mírně vlhká',
    sun: '⛅ Polostín, toleruje stín',
    watering: 'Mírně, odolná suchu',
    fertilizing: 'Kompost na jaře',
    pruning: 'Po odkvětu sekat celou rostlinu pro nový výraz',
    planting: 'Jaro nebo podzim',
    notes: 'Dekorativní kapky vody na listech. Skvělá jako podrost.',
    tasks: [
      { title: 'Zálivka kontryhelu', task_type: 'zalivka', frequency_days: 7 },
      { title: 'Seč kontryhelu', task_type: 'strihani', frequency_days: 365, notes: 'Po odkvětu sekat na 5 cm nad zemí' },
    ],
  },
  {
    id: 71,
    nameCz: 'Flox latnatý',
    nameLat: 'Phlox paniculata',
    soil: 'Výživná, humózní, propustná',
    sun: '☀️ Slunce',
    watering: '2× týdně',
    fertilizing: 'Na jaře a v červnu',
    pruning: 'Na podzim sekat na přízemí. Deadheadovat v průběhu léta.',
    planting: 'Jaro nebo podzim',
    notes: 'Náchylný na padlí — dobrá vzdušnost mezi rostlinami, neztěsnávat.',
    tasks: [
      { title: 'Zálivka floxu', task_type: 'zalivka', frequency_days: 4 },
      { title: 'Hnojení floxu', task_type: 'hnojeni', frequency_days: 30 },
      { title: 'Kontrola padlí na floxu', task_type: 'kontrola', frequency_days: 14 },
      { title: 'Podzimní seč floxu', task_type: 'strihani', frequency_days: 365, notes: 'Říjen–listopad: sekat na 5–10 cm nad zemí' },
    ],
  },
  {
    id: 72,
    nameCz: 'Astilba',
    nameLat: 'Astilbe',
    soil: 'Vlhká, humózní, stínotolerantní',
    sun: '🌥️ Stín nebo polostín, vlhko',
    watering: 'Hojně, nesmí vyschnout',
    fertilizing: 'Kompost každé jaro',
    pruning: 'Odkvetlé metly nechat pro zimní dekoraci, v únoru sekat',
    planting: 'Jaro nebo podzim, vlhké místo',
    notes: 'Nekrásit odkvetlé metly — jsou dekorativní v zimě a produkují semena.',
    tasks: [
      { title: 'Zálivka astilby', task_type: 'zalivka', frequency_days: 3 },
      { title: 'Hnojení astilby', task_type: 'hnojeni', frequency_days: 365, notes: 'Kompost na jaře' },
      { title: 'Jarní seč astilby', task_type: 'strihani', frequency_days: 365, notes: 'Únor–březen: sekat staré výhony' },
    ],
  },
  {
    id: 73,
    nameCz: 'Kopretina zahradní',
    nameLat: 'Leucanthemum × superbum',
    soil: 'Propustná, průměrná',
    sun: '☀️ Plné slunce',
    watering: '1–2× týdně',
    fertilizing: 'Na jaře lehce hnojit',
    pruning: 'Deadheadovat pro prodloužení kvetení. Na podzim sekat.',
    planting: 'Jaro nebo podzim',
    notes: 'Každé 3 roky rozdělit trs pro obnovu.',
    tasks: [
      { title: 'Zálivka kopretiny', task_type: 'zalivka', frequency_days: 5 },
      { title: 'Deadheading kopretiny', task_type: 'strihani', frequency_days: 10 },
      { title: 'Podzimní seč kopretiny', task_type: 'strihani', frequency_days: 365, notes: 'Říjen: sekat na přízemí' },
    ],
  },
  {
    id: 74,
    nameCz: 'Okrasná tráva (Miscanthus)',
    nameLat: 'Miscanthus sinensis',
    soil: 'Propustná, průměrná',
    sun: '☀️ Plné slunce',
    watering: 'Odolná suchu po zakotvení',
    fertilizing: 'Dusíkaté hnojivo na jaře',
    pruning: 'Nechat přes zimu (ptáci se krmí), sekat v únoru–březnu',
    planting: 'Jaro',
    notes: 'Nádherná v zimě s námrazou. Sekat krátce před rašením nových výhonů.',
    tasks: [
      { title: 'Zálivka miscanthusu', task_type: 'zalivka', frequency_days: 10 },
      { title: 'Jarní seč miscanthusu', task_type: 'strihani', frequency_days: 365, notes: 'Únor–březen: sekat na 10 cm nad zemí' },
    ],
  },
  {
    id: 75,
    nameCz: 'Čemeřice (Helleborus)',
    nameLat: 'Helleborus',
    soil: 'Humózní, propustná, vlhká',
    sun: '🌥️ Polostín až stín (pod listnatými stromy)',
    watering: 'Mírně pravidelně',
    fertilizing: 'Kompost na jaře',
    pruning: 'Na jaře odříznout staré listy před kvetením',
    planting: 'Podzim nebo jaro',
    notes: 'Kvete v únoru–březnu — první jarní květ! Toxická pro lidi i zvířata.',
    tasks: [
      { title: 'Zálivka čemeřice', task_type: 'zalivka', frequency_days: 7 },
      { title: 'Jarní úklid čemeřice', task_type: 'strihani', frequency_days: 365, notes: 'Únor: odříznout staré listy před kvetením' },
    ],
  },
  {
    id: 76,
    nameCz: 'Prvosenka (Primula)',
    nameLat: 'Primula vulgaris',
    soil: 'Humózní, vlhká, propustná',
    sun: '⛅ Polostín (jarní slunce OK)',
    watering: 'Pravidelně, nesmí vyschnout',
    fertilizing: 'Tekuté hnojivo 1× za 2 týdny na jaře',
    pruning: 'Po odkvětu odříznout odkvětlé stonky',
    planting: 'Podzim nebo brzy na jaře',
    notes: 'Klasická jarní trvalka. Přesadit po odkvětu do polostínu.',
    tasks: [
      { title: 'Zálivka prvosenky', task_type: 'zalivka', frequency_days: 3 },
      { title: 'Hnojení prvosenky', task_type: 'hnojeni', frequency_days: 14 },
    ],
  },
  {
    id: 77,
    nameCz: 'Kosatec (Iris)',
    nameLat: 'Iris germanica',
    soil: 'Propustná, neutrální až alkalická',
    sun: '☀️ Plné slunce',
    watering: 'Střídmě — přemokření vadí oddenky',
    fertilizing: 'Draselné hnojivo na jaře',
    pruning: 'Po odkvětu odříznout stonek. Na podzim zkrátit listy na 15 cm.',
    planting: 'Červenec–srpen (oddenky), mělce nad půdou',
    notes: 'Oddenky musí být viditelné nad zemí. Každé 3–4 roky rozdělit.',
    tasks: [
      { title: 'Zálivka kosatce', task_type: 'zalivka', frequency_days: 10 },
      { title: 'Řez kosatce po odkvětu', task_type: 'strihani', frequency_days: 365 },
      { title: 'Dělení kosatce', task_type: 'presazeni', frequency_days: 365, notes: 'Každé 3–4 roky: červenec, dělit oddenky' },
    ],
  },
  {
    id: 78,
    nameCz: 'Konvalinka',
    nameLat: 'Convallaria majalis',
    soil: 'Humózní, vlhká, stínotolerantní',
    sun: '🌥️ Stín nebo polostín',
    watering: 'Pravidelně, nesmí vyschnout',
    fertilizing: 'Kompost na podzim',
    pruning: 'Listy nechat do podzimu',
    planting: 'Podzim — oddenky s poupaty',
    notes: 'Celá rostlina silně jedovatá! Invazivní — rozkládá se oddenky. Krásná vůně.',
    tasks: [
      { title: 'Zálivka konvalinky', task_type: 'zalivka', frequency_days: 5 },
      { title: 'Podzimní hnojení', task_type: 'hnojeni', frequency_days: 365, notes: 'Říjen: kompost nebo organické hnojivo' },
    ],
  },
  {
    id: 79,
    nameCz: 'Denivka (Hemerocallis)',
    nameLat: 'Hemerocallis',
    soil: 'Humózní, propustná, průměrná',
    sun: '☀️ Slunce i polostín',
    watering: '1–2× týdně',
    fertilizing: 'Na jaře kompost nebo NPK',
    pruning: 'Deadheadovat. Na podzim sekat na přízemí.',
    planting: 'Jaro nebo podzim, velmi nenáročná',
    notes: 'Každý květ kvete 1 den — ale kvetení trvá týdny. Skvělá pro začátečníky.',
    tasks: [
      { title: 'Zálivka denivky', task_type: 'zalivka', frequency_days: 5 },
      { title: 'Deadheading denivky', task_type: 'strihani', frequency_days: 7 },
      { title: 'Podzimní seč denivky', task_type: 'strihani', frequency_days: 365, notes: 'Říjen: sekat na 10 cm nad zemí' },
    ],
  },
  {
    id: 80,
    nameCz: 'Alyssum (Lobularia)',
    nameLat: 'Lobularia maritima',
    soil: 'Chudá, propustná',
    sun: '☀️ Slunce',
    watering: 'Mírně',
    fertilizing: 'Minimálně',
    pruning: 'Nastřihnout po první vlně kvetení pro obnovu',
    planting: 'Přímo sít od dubna nebo přesazovat po 15. května',
    notes: 'Výborná pro lemování záhonů a do spár. Příjemná medonosná vůně.',
    tasks: [
      { title: 'Zálivka alyssum', task_type: 'zalivka', frequency_days: 5 },
      { title: 'Nastřihávání alyssum', task_type: 'strihani', frequency_days: 30, notes: 'Nastřihnout o třetinu pro obnovu kvetení' },
    ],
  },
  {
    id: 81,
    nameCz: 'Rezeda vonná',
    nameLat: 'Reseda odorata',
    soil: 'Propustná, lehce vápnitá',
    sun: '☀️ Slunce',
    watering: 'Mírně',
    fertilizing: 'Minimálně',
    pruning: 'Deadheadovat pro delší kvetení',
    planting: 'Přímo sít duben–červen',
    notes: 'Intenzivní vůně. Jednoletá. Výborná do řezaných kytic.',
    tasks: [
      { title: 'Zálivka rezedy', task_type: 'zalivka', frequency_days: 5 },
      { title: 'Deadheading rezedy', task_type: 'strihani', frequency_days: 10 },
    ],
  },
  {
    id: 82,
    nameCz: 'Pryskyřník plazivý (okrasný)',
    nameLat: 'Ranunculus acris / Ranunculus repens',
    soil: 'Vlhká, humózní',
    sun: '⛅ Polostín',
    watering: 'Pravidelně vlhká půda',
    fertilizing: 'Kompost na jaře',
    pruning: 'Odstraňovat přerostlé výhony',
    planting: 'Jaro',
    notes: 'Invazivní — kontrolovat šíření. Jedovatý při požití.',
    tasks: [
      { title: 'Zálivka pryskyřníku', task_type: 'zalivka', frequency_days: 5 },
      { title: 'Kontrola šíření', task_type: 'kontrola', frequency_days: 21 },
    ],
  },
  {
    id: 83,
    nameCz: 'Fíkovník (fík)',
    nameLat: 'Ficus carica',
    soil: 'Propustná, kamenitá nebo písčitá',
    sun: '☀️ Plné slunce, chráněné od větru',
    watering: 'Hojně v létě, na podzim omezit',
    fertilizing: 'Každých 14 dní v červnu–červenci draselným hnojivem',
    pruning: 'Jarní prosvětlení, letní zkracování pro tvar',
    planting: 'Jaro, nejlépe v nádobě pro přezimování',
    notes: 'V ČR přezimovat přikrytím nebo v chladné místnosti. Plody dozrávají na loňském dřevě.',
    tasks: [
      { title: 'Zálivka fíku', task_type: 'zalivka', frequency_days: 4 },
      { title: 'Hnojení fíku', task_type: 'hnojeni', frequency_days: 14 },
      { title: 'Zimní ochrana fíku', task_type: 'jine', frequency_days: 365, notes: 'Říjen: přikrýt jutou nebo přenést do chladné místnosti' },
      { title: 'Sklizeň fíků', task_type: 'sklizen', frequency_days: 3, notes: 'Sbírat měkké, zralé plody (srpen–říjen)' },
    ],
  },
  {
    id: 84,
    nameCz: 'Echinacea (třapatka)',
    nameLat: 'Echinacea purpurea',
    soil: 'Propustná, suchá až průměrná',
    sun: '☀️ Plné slunce',
    watering: 'Odolná suchu po zakotvení',
    fertilizing: 'Kompost na jaře, jinak chudá půda stačí',
    pruning: 'Odkvetlé hlavy nechat — ptáci žerou semena. Sekat na jaře.',
    planting: 'Jaro nebo podzim, vytrvalá trvalka',
    notes: 'Léčivá — imunita. Výborná pro motýly a včely. Samoobnovující se.',
    tasks: [
      { title: 'Zálivka echinacei', task_type: 'zalivka', frequency_days: 7 },
      { title: 'Jarní seč echinacei', task_type: 'strihani', frequency_days: 365, notes: 'Únor–březen: sekat na 5–10 cm' },
    ],
  },
  {
    id: 85,
    nameCz: 'Agapanthus',
    nameLat: 'Agapanthus',
    soil: 'Propustná, středně výživná',
    sun: '☀️ Plné slunce',
    watering: 'Hojně v létě, téměř nic v zimě',
    fertilizing: 'Draselné hnojivo v létě pro kvetení',
    pruning: 'Po odkvětu odříznout stonky',
    planting: 'Nádoba — přenést ven po 15. května, přezimovat uvnitř',
    notes: 'Nesnáší mráz. Přezimovat v chladné místnosti 5–10 °C, sucho.',
    tasks: [
      { title: 'Zálivka agapanthusu', task_type: 'zalivka', frequency_days: 4 },
      { title: 'Hnojení agapanthusu', task_type: 'hnojeni', frequency_days: 21, notes: 'Draselné hnojivo pro kvetení' },
      { title: 'Přezimování agapanthusu', task_type: 'presazeni', frequency_days: 365, notes: 'Říjen: přenést do chladu 5–10 °C, minimálně zalévat' },
    ],
  },
];

// ==================== KATEGORIE ROSTLIN ====================
// Mapování ID → kategorie (slouží pro placeholder ikony, badge, filtrování)
export function getPlantCategory(id) {
  if (id <= 20) return { key: 'zelenina', label: 'Zelenina', icon: '🥕', color: '#5a9a4d' };
  if (id <= 26) return { key: 'ovoce', label: 'Ovoce', icon: '🍓', color: '#c0392b' };
  if (id <= 40) return { key: 'bylinky', label: 'Bylinky', icon: '🌿', color: '#4a7c3a' };
  if (id <= 50) return { key: 'okrasne', label: 'Okrasné', icon: '🌸', color: '#c2185b' };
  if (id <= 56) return { key: 'cibuloviny', label: 'Cibuloviny', icon: '🌷', color: '#8e44ad' };
  if (id <= 66) return { key: 'kere', label: 'Keře a stromy', icon: '🌳', color: '#2d5a27' };
  return { key: 'trvalky', label: 'Trvalky', icon: '🌼', color: '#d97a1b' };
}

// ==================== ROZŠÍŘENÁ METADATA ====================
// Doplňující údaje pro karty v novém designu: zone, light, water, height, careActions
// Pro ID, která zde nejsou, se hodnoty odvodí z původních polí sun/watering.
const PLANT_META = {
  1: { zone: '5-9', light: 'Plné slunce', water: 'Hojná', height: '120-200 cm',
       careActions: [
         { text: 'Zápichové kolíky', month: 5, emoji: '🪵' },
         { text: 'Pasínkovat výhony', month: 7, emoji: '✂️' },
         { text: 'Postřik proti plísni', month: 7, emoji: '🛡️' },
       ] },
  2: { zone: '6-10', light: 'Plné slunce', water: 'Mírná', height: '40-80 cm',
       careActions: [
         { text: 'Pinzovat vršky pro větvení', month: 6, emoji: '✂️' },
         { text: 'Hnojení plodů', month: 7, emoji: '🌱' },
       ] },
  3: { zone: '5-9', light: 'Plné slunce', water: 'Hojná', height: '150-200 cm',
       careActions: [
         { text: 'Pravidelná sklizeň', month: 7, emoji: '🥒' },
         { text: 'Postřik proti padlí', month: 7, emoji: '🛡️' },
       ] },
  4: { zone: '4-9', light: 'Polostín', water: 'Mírná', height: '20-30 cm',
       careActions: [
         { text: 'Postupný výsev', month: 4, emoji: '🌱' },
       ] },
  5: { zone: '3-10', light: 'Plné slunce', water: 'Mírná', height: '20-30 cm',
       careActions: [
         { text: 'Prokypřit půdu před setím', month: 4, emoji: '🪴' },
         { text: 'Prořezat výsev', month: 5, emoji: '✂️' },
       ] },
  6: { zone: '4-9', light: 'Plné slunce', water: 'Nízká', height: '20-40 cm',
       careActions: [
         { text: 'Sázet sazečku', month: 3, emoji: '🌱' },
         { text: 'Přestat zalévat (zrání)', month: 7, emoji: '☀️' },
         { text: 'Sklizeň po poléhání natě', month: 8, emoji: '🧺' },
       ] },
  7: { zone: '4-9', light: 'Plné slunce', water: 'Nízká', height: '30-50 cm',
       careActions: [
         { text: 'Sázet ozimý česnek', month: 10, emoji: '🌱' },
         { text: 'Odstranit šla (květní stvoly)', month: 6, emoji: '✂️' },
         { text: 'Sklizeň po žloutnutí natě', month: 7, emoji: '🧺' },
       ] },
  8: { zone: '4-10', light: 'Plné slunce', water: 'Hojná', height: '30-50 cm (popínavá)',
       careActions: [
         { text: 'Vysadit po mrazech', month: 5, emoji: '🌱' },
         { text: 'Zkrátit výhony (2-3 plody)', month: 7, emoji: '✂️' },
         { text: 'Sklizeň před mrazy', month: 9, emoji: '🎃' },
       ] },
  9: { zone: '4-10', light: 'Plné slunce', water: 'Hojná', height: '60-100 cm',
       careActions: [
         { text: 'Vysadit po mrazech', month: 5, emoji: '🌱' },
         { text: 'Sklizeň při 15-20 cm', month: 7, emoji: '🥒' },
         { text: 'Odstranit staré listy', month: 8, emoji: '✂️' },
       ] },
  10: { zone: '3-10', light: 'Plné slunce', water: 'Mírná', height: '40-60 cm',
        careActions: [
          { text: 'Přímý výsev po 8 cm', month: 5, emoji: '🌱' },
          { text: 'Pravidelná sklizeň lusků', month: 7, emoji: '🧺' },
        ] },
  11: { zone: '3-9', light: 'Plné slunce', water: 'Mírná', height: '50-200 cm',
        careActions: [
          { text: 'Brzký jarní výsev', month: 3, emoji: '🌱' },
          { text: 'Postavit opory', month: 4, emoji: '🪵' },
          { text: 'Sklizeň před plným zráním', month: 6, emoji: '🧺' },
        ] },
  12: { zone: '3-9', light: 'Polostín', water: 'Mírná', height: '15-30 cm',
        careActions: [
          { text: 'Jarní výsev', month: 3, emoji: '🌱' },
          { text: 'Sklizeň vnějších listů', month: 5, emoji: '🧺' },
          { text: 'Podzimní výsev', month: 9, emoji: '🌱' },
        ] },
  13: { zone: '3-10', light: 'Plné slunce', water: 'Mírná', height: '40-80 cm',
        careActions: [
          { text: 'Přesazovat sazenice', month: 5, emoji: '🌱' },
          { text: 'Hnojení dusíkem', month: 6, emoji: '🌿' },
          { text: 'Kontrola housenek bělásků', month: 7, emoji: '🐛' },
        ] },
  14: { zone: '4-9', light: 'Plné slunce', water: 'Mírná', height: '20-30 cm',
        careActions: [
          { text: 'Výsev / přesadit', month: 4, emoji: '🌱' },
          { text: 'Sklizeň při 6-8 cm', month: 6, emoji: '🧺' },
        ] },
  15: { zone: '3-9', light: 'Plné slunce', water: 'Hojná', height: '30-50 cm',
        careActions: [
          { text: 'Přesadit sazenice', month: 5, emoji: '🌱' },
          { text: 'Druhá dávka dusíku', month: 7, emoji: '🌿' },
          { text: 'Kontrola housenek', month: 7, emoji: '🐛' },
        ] },
  17: { zone: '2-10', light: 'Plné slunce', water: 'Mírná', height: '10-20 cm',
        careActions: [
          { text: 'První výsev (každé 2-3 týdny)', month: 3, emoji: '🌱' },
          { text: 'Druhý výsev', month: 5, emoji: '🌱' },
          { text: 'Podzimní výsev', month: 8, emoji: '🌱' },
        ] },
  24: { zone: '3-7', light: 'Plné slunce', water: 'Mírná', height: '100-150 cm',
        careActions: [
          { text: 'Zimní řez (větve > 3 roky)', month: 2, emoji: '✂️' },
          { text: 'Kompost na jaře', month: 4, emoji: '🌱' },
          { text: 'Síť proti ptákům', month: 6, emoji: '🛡️' },
        ] },
  25: { zone: '3-7', light: 'Polostín', water: 'Mírná', height: '80-120 cm',
        careActions: [
          { text: 'Letní zkracování výhonů', month: 7, emoji: '✂️' },
          { text: 'Zimní prosvětlení', month: 2, emoji: '✂️' },
          { text: 'Postřik proti padlí', month: 5, emoji: '🛡️' },
        ] },
  31: { zone: '5-9', light: 'Plné slunce', water: 'Nízká', height: '30-60 cm',
        careActions: [
          { text: 'Zkrátit po odkvětu', month: 8, emoji: '✂️' },
          { text: 'Jarní omlazovací řez', month: 4, emoji: '✂️' },
        ] },
  32: { zone: '3-9', light: 'Plné slunce', water: 'Mírná', height: '20-40 cm',
        careActions: [
          { text: 'Dělit přerostlé trsy', month: 4, emoji: '🪴' },
          { text: 'Odstranit fialové květy', month: 6, emoji: '✂️' },
        ] },
  35: { zone: '5-9', light: 'Plné slunce', water: 'Nízká', height: '30-60 cm',
        careActions: [
          { text: 'Řez po odkvětu (o třetinu)', month: 8, emoji: '✂️' },
          { text: 'Odstranit suché výhony', month: 4, emoji: '✂️' },
          { text: 'Sklizeň květů na sušení', month: 7, emoji: '💜' },
        ] },
  40: { zone: '4-10', light: 'Plné slunce', water: 'Mírná', height: '60-200 cm',
        careActions: [
          { text: 'Jarní řez na 3-5 oček', month: 3, emoji: '✂️' },
          { text: 'Hnojení od dubna', month: 4, emoji: '🌱' },
          { text: 'Postřik proti mšicím', month: 5, emoji: '🛡️' },
          { text: 'Zimní zábal', month: 11, emoji: '🛡️' },
        ] },
  50: { zone: '9-11', light: 'Plné slunce', water: 'Hojná', height: '20-40 cm',
        careActions: [
          { text: 'Vysadit ven', month: 5, emoji: '🌱' },
          { text: 'Zastřihnout pro větvení', month: 7, emoji: '✂️' },
        ] },
  52: { zone: '3-8', light: 'Plné slunce', water: 'Nízká', height: '20-60 cm',
        careActions: [
          { text: 'Sázet cibule (15 cm hluboko)', month: 10, emoji: '🌱' },
          { text: 'Po odkvětu nechat zaschnout listy', month: 5, emoji: '🌿' },
        ] },
  21: { zone: '4-9', light: 'Plné slunce', water: 'Mírná', height: '15-25 cm',
        careActions: [
          { text: 'Odstranit šlahouny', month: 6, emoji: '✂️' },
          { text: 'Mulčování slámou', month: 5, emoji: '🌾' },
          { text: 'Omlazení po sklizni', month: 8, emoji: '✂️' },
        ] },
  22: { zone: '3-9', light: 'Plné slunce', water: 'Mírná', height: '150-200 cm',
        careActions: [
          { text: 'Vyřezat odplozené výhony', month: 9, emoji: '✂️' },
          { text: 'Jarní hnojení kompostem', month: 3, emoji: '🌱' },
        ] },
  23: { zone: '3-7', light: 'Polostín', water: 'Hojná', height: '80-150 cm',
        careActions: [
          { text: 'Mulčovat kyselou kůrou', month: 4, emoji: '🌾' },
          { text: 'Řez starých větví', month: 3, emoji: '✂️' },
        ] },
  27: { zone: '4-10', light: 'Plné slunce', water: 'Mírná', height: '30-50 cm',
        careActions: [
          { text: 'Pinzovat vrcholky pro keřovitý růst', month: 6, emoji: '✂️' },
          { text: 'Sklizeň před květem', month: 7, emoji: '🌿' },
        ] },
  28: { zone: '5-9', light: 'Plné slunce', water: 'Nízká', height: '20-30 cm',
        careActions: [
          { text: 'Jarní zastřižení', month: 4, emoji: '✂️' },
        ] },
  29: { zone: '7-10', light: 'Plné slunce', water: 'Nízká', height: '60-150 cm',
        careActions: [
          { text: 'Tvarovací řez', month: 4, emoji: '✂️' },
          { text: 'Zimní zábal v chladné oblasti', month: 11, emoji: '🛡️' },
        ] },
  30: { zone: '3-11', light: 'Polostín', water: 'Hojná', height: '30-80 cm',
        careActions: [
          { text: 'Sázet do nádoby (omezuje kořeny)', month: 4, emoji: '🪴' },
          { text: 'Zastřižení po odkvětu', month: 8, emoji: '✂️' },
        ] },
  34: { zone: '5-9', light: 'Plné slunce', water: 'Nízká', height: '40-80 cm',
        careActions: [
          { text: 'Zastřihnout po odkvětu', month: 8, emoji: '✂️' },
          { text: 'Jarní omlazovací řez', month: 4, emoji: '✂️' },
        ] },
  41: { zone: '4-9', light: 'Plné slunce', water: 'Mírná', height: '60-200 cm',
        careActions: [
          { text: 'Jarní řez na 3-5 oček', month: 3, emoji: '✂️' },
          { text: 'Hnojení po prvním květu', month: 6, emoji: '🌱' },
          { text: 'Zimní zábal', month: 11, emoji: '🛡️' },
        ] },
  42: { zone: '4-9', light: 'Polostín', water: 'Hojná', height: '100-200 cm',
        careActions: [
          { text: 'Zastřihnout po odkvětu', month: 8, emoji: '✂️' },
          { text: 'Přihnojit na jaře', month: 4, emoji: '🌱' },
          { text: 'Zimní zábal pro citlivé kultivary', month: 11, emoji: '🛡️' },
        ] },
  43: { zone: '3-7', light: 'Plné slunce', water: 'Mírná', height: '300-500 cm',
        careActions: [
          { text: 'Zastřihnout po odkvětu', month: 6, emoji: '✂️' },
          { text: 'Odstranit kořenové výmladky', month: 6, emoji: '✂️' },
        ] },
  44: { zone: '9-11', light: 'Plné slunce', water: 'Mírná', height: '30-60 cm',
        careActions: [
          { text: 'Odstraňovat odkvetlé květy', month: 7, emoji: '✂️' },
          { text: 'Přezimovat v chladu 5-10°C', month: 10, emoji: '🛡️' },
        ] },
  47: { zone: '4-9', light: 'Plné slunce', water: 'Hojná', height: '100-300 cm',
        careActions: [
          { text: 'Vázat ke kůlu při růstu', month: 6, emoji: '🪵' },
        ] },
  51: { zone: '3-8', light: 'Plné slunce', water: 'Mírná', height: '20-60 cm',
        careActions: [
          { text: 'Sázet cibule na podzim', month: 10, emoji: '🌱' },
          { text: 'Po odkvětu nechat zaschnout listy', month: 6, emoji: '🌿' },
        ] },
  55: { zone: '3-9', light: 'Plné slunce', water: 'Mírná', height: '60-180 cm',
        careActions: [
          { text: 'Mulčování kořenů', month: 5, emoji: '🌾' },
          { text: 'Odstranit semenáky', month: 8, emoji: '✂️' },
        ] },
  57: { zone: '5-8', light: 'Polostín', water: 'Mírná', height: '50-300 cm',
        careActions: [
          { text: 'Tvarovací řez', month: 6, emoji: '✂️' },
          { text: 'Postřik proti zápalu', month: 5, emoji: '🛡️' },
        ] },
  60: { zone: '4-9', light: 'Polostín', water: 'Mírná', height: '300-800 cm',
        careActions: [
          { text: 'Mulčovat kořeny', month: 4, emoji: '🌾' },
          { text: 'Pouze prosvětlovací řez po odkvětu', month: 6, emoji: '✂️' },
        ] },
  61: { zone: '5-9', light: 'Polostín', water: 'Hojná', height: '200-600 cm',
        careActions: [
          { text: 'Kontrola šíření kořenů', month: 4, emoji: '🛡️' },
          { text: 'Vyřezat staré stvoly', month: 3, emoji: '✂️' },
        ] },
  64: { zone: '3-8', light: 'Plné slunce', water: 'Mírná', height: '150-250 cm',
        careActions: [
          { text: 'Silný jarní řez na 2-3 očka', month: 3, emoji: '✂️' },
          { text: 'Přihnojit kompostem', month: 4, emoji: '🌱' },
        ] },
  70: { zone: '4-8', light: 'Plné slunce', water: 'Mírná', height: '60-120 cm',
        careActions: [
          { text: 'Řez na jaře před rašením', month: 3, emoji: '✂️' },
          { text: 'Dělit trsy každé 3-4 roky', month: 4, emoji: '🪴' },
        ] },
  71: { zone: '3-8', light: 'Stín', water: 'Hojná', height: '40-100 cm',
        careActions: [
          { text: 'Mulčování pro vlhkost', month: 5, emoji: '🌾' },
          { text: 'Řez na podzim', month: 10, emoji: '✂️' },
        ] },
  73: { zone: '4-9', light: 'Plné slunce', water: 'Mírná', height: '120-250 cm',
        careActions: [
          { text: 'Zastřihnout do konce března', month: 3, emoji: '✂️' },
          { text: 'Přihnojit na jaře', month: 4, emoji: '🌱' },
        ] },
  76: { zone: '3-9', light: 'Plné slunce', water: 'Mírná', height: '40-100 cm',
        careActions: [
          { text: 'Dělit oddenky každé 3-4 roky', month: 8, emoji: '🪴' },
          { text: 'Odstranit suché listy', month: 10, emoji: '✂️' },
        ] },
  84: { zone: '3-9', light: 'Plné slunce', water: 'Nízká', height: '60-120 cm',
        careActions: [
          { text: 'Jarní seč na 5-10 cm', month: 3, emoji: '✂️' },
          { text: 'Nechat odkvetlé hlavy pro ptáky', month: 10, emoji: '🐦' },
        ] },
  16: { zone: '4-9', light: 'Plné slunce', water: 'Mírná', height: '40-80 cm',
        careActions: [
          { text: 'Předpěstovat sazenice', month: 3, emoji: '🌱' },
          { text: 'Přesadit do záhonu', month: 6, emoji: '🌱' },
          { text: 'Obrývat pro bílání', month: 8, emoji: '🪴' },
          { text: 'Sklizeň', month: 10, emoji: '🧺' },
        ] },
  18: { zone: '4-9', light: 'Plné slunce', water: 'Mírná', height: '40-60 cm',
        careActions: [
          { text: 'Přímý výsev', month: 4, emoji: '🌱' },
          { text: 'Sklizeň vnějších listů', month: 7, emoji: '🧺' },
          { text: 'Pokračující sklizeň do mrazu', month: 9, emoji: '🧺' },
        ] },
  19: { zone: '4-9', light: 'Plné slunce', water: 'Mírná', height: '20-40 cm',
        careActions: [
          { text: 'Přímý výsev (klíčí 3 týdny)', month: 4, emoji: '🌱' },
          { text: 'Pletí výsevu', month: 6, emoji: '🌿' },
          { text: 'Sklizeň kořenů', month: 10, emoji: '🧺' },
        ] },
  20: { zone: '4-10', light: 'Plné slunce', water: 'Hojná', height: '40-60 cm',
        careActions: [
          { text: 'Vysadit po mrazech', month: 5, emoji: '🌱' },
          { text: 'Hnojení', month: 6, emoji: '🌿' },
          { text: 'Sklizeň mladých plodů', month: 7, emoji: '🥒' },
        ] },
  26: { zone: '5-9', light: 'Plné slunce', water: 'Mírná', height: '150-250 cm',
        careActions: [
          { text: 'Přivázat nové výhony k drátěnce', month: 5, emoji: '🪵' },
          { text: 'Sklizeň zralých plodů', month: 8, emoji: '🧺' },
          { text: 'Vyřezat dvouleté výhony', month: 9, emoji: '✂️' },
        ] },
  33: { zone: '5-9', light: 'Plné slunce', water: 'Nízká', height: '30-60 cm',
        careActions: [
          { text: 'Seč před květem', month: 6, emoji: '✂️' },
          { text: 'Sušení na svazečky', month: 7, emoji: '🌿' },
        ] },
  36: { zone: '4-10', light: 'Plné slunce', water: 'Mírná', height: '30-60 cm',
        careActions: [
          { text: 'První přímý výsev', month: 4, emoji: '🌱' },
          { text: 'Opakovat výsev (každé 3 týdny)', month: 6, emoji: '🌱' },
          { text: 'Sklizeň před květem', month: 7, emoji: '🌿' },
        ] },
  37: { zone: '5-9', light: 'Plné slunce', water: 'Nízká', height: '60-120 cm',
        careActions: [
          { text: 'Dělení trsů na jaře', month: 3, emoji: '🪴' },
          { text: 'Seč před květem', month: 6, emoji: '✂️' },
        ] },
  38: { zone: '3-9', light: 'Plné slunce', water: 'Nízká', height: '20-50 cm',
        careActions: [
          { text: 'Přímý výsev', month: 3, emoji: '🌱' },
          { text: 'Sklizeň květů ráno', month: 6, emoji: '🌼' },
          { text: 'Nechat dozrát semena pro samosev', month: 8, emoji: '🌾' },
        ] },
  39: { zone: '4-9', light: 'Plné slunce', water: 'Nízká', height: '30-80 cm',
        careActions: [
          { text: 'Sklizeň kvetoucích vrcholků', month: 7, emoji: '🌿' },
          { text: 'Seč po odkvětu pro větvení', month: 8, emoji: '✂️' },
        ] },
  45: { zone: '9-11', light: 'Polostín', water: 'Mírná', height: '20-40 cm',
        careActions: [
          { text: 'Předpěstovat hlízy', month: 3, emoji: '🌱' },
          { text: 'Vysadit ven', month: 5, emoji: '🌱' },
          { text: 'Vykopat hlízy před mrazem', month: 10, emoji: '🛡️' },
        ] },
  46: { zone: '8-11', light: 'Plné slunce', water: 'Hojná', height: '60-150 cm',
        careActions: [
          { text: 'Sázet hlízy po mrazech', month: 5, emoji: '🌱' },
          { text: 'Pinzovat první výhony', month: 6, emoji: '✂️' },
          { text: 'Hnojení draslíkem', month: 7, emoji: '🌿' },
          { text: 'Vykopat hlízy po prvním mrazu', month: 10, emoji: '🛡️' },
        ] },
  48: { zone: '2-11', light: 'Plné slunce', water: 'Nízká', height: '40-80 cm',
        careActions: [
          { text: 'Přímý výsev', month: 4, emoji: '🌱' },
          { text: 'Deadheading pro delší kvetení', month: 7, emoji: '✂️' },
        ] },
  49: { zone: '2-11', light: 'Plné slunce', water: 'Mírná', height: '30-60 cm',
        careActions: [
          { text: 'Přímý výsev', month: 4, emoji: '🌱' },
          { text: 'Sklizeň květů na mast', month: 6, emoji: '🌼' },
          { text: 'Deadheading', month: 7, emoji: '✂️' },
        ] },
  53: { zone: '3-9', light: 'Plné slunce', water: 'Nízká', height: '20-40 cm',
        careActions: [
          { text: 'Výsadba cibulí (10-15 cm hluboko)', month: 9, emoji: '🌱' },
          { text: 'Deadheading po odkvětu', month: 5, emoji: '✂️' },
          { text: 'Nechat listy zaschnout', month: 6, emoji: '🌿' },
        ] },
  54: { zone: '4-8', light: 'Plné slunce', water: 'Nízká', height: '20-30 cm',
        careActions: [
          { text: 'Výsadba cibulí (10 cm hluboko)', month: 10, emoji: '🌱' },
          { text: 'Deadheading po odkvětu', month: 5, emoji: '✂️' },
        ] },
  56: { zone: '3-9', light: 'Plné slunce', water: 'Mírná', height: '60-180 cm',
        careActions: [
          { text: 'Mulčovat kořen pro chlad', month: 4, emoji: '🌾' },
          { text: 'Kontrola červených brouků', month: 6, emoji: '🐛' },
          { text: 'Výsadba cibulí (15-20 cm)', month: 10, emoji: '🌱' },
        ] },
  58: { zone: '5-9', light: 'Polostín', water: 'Mírná', height: '50-200 cm',
        careActions: [
          { text: 'Kontrola housenky buxusové', month: 5, emoji: '🐛' },
          { text: 'První tvarovací řez', month: 6, emoji: '✂️' },
          { text: 'Druhé tvarování', month: 8, emoji: '✂️' },
        ] },
  59: { zone: '5-8', light: 'Polostín', water: 'Hojná', height: '100-300 cm',
        careActions: [
          { text: 'Kyselé hnojivo (pro azalky)', month: 4, emoji: '🌱' },
          { text: 'Mulčování rašelinou', month: 5, emoji: '🌾' },
          { text: 'Deadheading odkvetlých hroznů', month: 6, emoji: '✂️' },
        ] },
  62: { zone: '4-8', light: 'Plné slunce', water: 'Nízká', height: '60-200 cm',
        careActions: [
          { text: 'Jarní prosvětlení (rukavice!)', month: 3, emoji: '✂️' },
          { text: 'Tvarování po odkvětu', month: 6, emoji: '✂️' },
        ] },
  63: { zone: '4-9', light: 'Plné slunce', water: 'Mírná', height: '300-500 cm',
        careActions: [
          { text: 'Zimní prosvětlovací řez', month: 2, emoji: '✂️' },
          { text: 'Sklizeň ořechů', month: 9, emoji: '🌰' },
        ] },
  65: { zone: '5-9', light: 'Plné slunce', water: 'Mírná', height: '300-800 cm',
        careActions: [
          { text: 'Hnojení kyselé', month: 4, emoji: '🌱' },
          { text: 'Mulčování', month: 5, emoji: '🌾' },
          { text: 'Minimální řez (jen suché větve)', month: 6, emoji: '✂️' },
        ] },
  66: { zone: '5-9', light: 'Polostín', water: 'Mírná', height: '200-500 cm',
        careActions: [
          { text: 'Vyřezat odumřelé kulmy', month: 3, emoji: '✂️' },
          { text: 'Hnojení dusíkem', month: 4, emoji: '🌿' },
          { text: 'Kontrola kořenové bariéry', month: 5, emoji: '🛡️' },
        ] },
  67: { zone: '5-9', light: 'Plné slunce', water: 'Mírná', height: '500-1000 cm',
        careActions: [
          { text: 'Zimní řez na 2-3 oka', month: 2, emoji: '✂️' },
          { text: 'Hnojení draslíkem (ne dusík!)', month: 5, emoji: '🌿' },
          { text: 'Letní řez nových výhonů na 5 listů', month: 7, emoji: '✂️' },
        ] },
  68: { zone: '4-8', light: 'Plné slunce', water: 'Mírná', height: '150-250 cm',
        careActions: [
          { text: 'Zimní řez na 2-3 oka', month: 3, emoji: '✂️' },
          { text: 'Hnojení pro kvetoucí dřeviny', month: 4, emoji: '🌱' },
        ] },
  69: { zone: '3-8', light: 'Polostín', water: 'Nízká', height: '20-40 cm',
        careActions: [
          { text: 'Odstranit suché zimní listy', month: 3, emoji: '✂️' },
          { text: 'Mulčování kompostem', month: 4, emoji: '🌱' },
        ] },
  72: { zone: '3-8', light: 'Stín', water: 'Hojná', height: '40-100 cm',
        careActions: [
          { text: 'Jarní seč starých výhonů', month: 3, emoji: '✂️' },
          { text: 'Mulčování pro vlhkost', month: 4, emoji: '🌾' },
        ] },
  74: { zone: '5-9', light: 'Plné slunce', water: 'Nízká', height: '100-300 cm',
        careActions: [
          { text: 'Jarní seč na 10 cm', month: 3, emoji: '✂️' },
          { text: 'Hnojení dusíkem', month: 4, emoji: '🌿' },
        ] },
  75: { zone: '4-8', light: 'Polostín', water: 'Mírná', height: '20-50 cm',
        careActions: [
          { text: 'Odříznout staré listy před kvetením', month: 2, emoji: '✂️' },
          { text: 'Mulčování kompostem', month: 10, emoji: '🌾' },
        ] },
  77: { zone: '3-9', light: 'Plné slunce', water: 'Nízká', height: '40-100 cm',
        careActions: [
          { text: 'Hnojení draslíkem', month: 4, emoji: '🌿' },
          { text: 'Řez stonku po odkvětu', month: 6, emoji: '✂️' },
          { text: 'Dělení oddenků (každé 3-4 roky)', month: 8, emoji: '🪴' },
        ] },
  78: { zone: '3-8', light: 'Stín', water: 'Mírná', height: '15-30 cm',
        careActions: [
          { text: 'Výsadba oddenků', month: 9, emoji: '🌱' },
          { text: 'Podzimní hnojení kompostem', month: 10, emoji: '🌱' },
        ] },
  79: { zone: '3-9', light: 'Plné slunce', water: 'Mírná', height: '40-100 cm',
        careActions: [
          { text: 'Hnojení NPK', month: 4, emoji: '🌿' },
          { text: 'Deadheading', month: 7, emoji: '✂️' },
          { text: 'Podzimní seč na 10 cm', month: 10, emoji: '✂️' },
        ] },
  80: { zone: '5-10', light: 'Plné slunce', water: 'Nízká', height: '10-20 cm',
        careActions: [
          { text: 'Přímý výsev', month: 4, emoji: '🌱' },
          { text: 'Vysadit ven', month: 5, emoji: '🌱' },
          { text: 'Nastřihnout pro obnovu kvetení', month: 7, emoji: '✂️' },
        ] },
  81: { zone: '5-10', light: 'Plné slunce', water: 'Nízká', height: '30-60 cm',
        careActions: [
          { text: 'Přímý výsev', month: 4, emoji: '🌱' },
          { text: 'Deadheading pro delší kvetení', month: 6, emoji: '✂️' },
        ] },
  82: { zone: '4-8', light: 'Polostín', water: 'Hojná', height: '20-50 cm',
        careActions: [
          { text: 'Mulčování pro vlhkost', month: 4, emoji: '🌾' },
          { text: 'Kontrola invazivního šíření', month: 6, emoji: '🛡️' },
        ] },
  83: { zone: '7-10', light: 'Plné slunce', water: 'Mírná', height: '200-400 cm',
        careActions: [
          { text: 'Jarní prosvětlení', month: 3, emoji: '✂️' },
          { text: 'Hnojení draslíkem', month: 6, emoji: '🌿' },
          { text: 'Sklizeň zralých plodů', month: 8, emoji: '🧺' },
          { text: 'Zimní ochrana (juta nebo přesun)', month: 10, emoji: '🛡️' },
        ] },
  85: { zone: '8-11', light: 'Plné slunce', water: 'Hojná', height: '60-100 cm',
        careActions: [
          { text: 'Přesadit ven', month: 5, emoji: '🌱' },
          { text: 'Hnojení draslíkem pro kvetení', month: 6, emoji: '🌿' },
          { text: 'Přezimovat v chladu 5-10°C', month: 10, emoji: '🛡️' },
        ] },
};

// Odvození zjednodušeného popisku světla z původního "sun" textu
function deriveLight(sun) {
  if (!sun) return 'Plné slunce';
  const s = sun.toLowerCase();
  if (s.includes('stín') && !s.includes('polostín')) return 'Stín';
  if (s.includes('polostín') || s.includes('⛅')) return 'Polostín';
  return 'Plné slunce';
}

// Odvození zjednodušeného popisku zálivky
function deriveWater(watering) {
  if (!watering) return 'Mírná';
  const w = watering.toLowerCase();
  if (w.includes('denně') || w.includes('hojně') || w.includes('hojná')) return 'Hojná';
  if (w.includes('méně') || w.includes('odolná') || w.includes('nízká') || w.includes('sucho')) return 'Nízká';
  return 'Mírná';
}

// Obohať záznam o nové vlastnosti pro karty (volat všude, kde se používá v UI)
export function enrichPlant(plant) {
  if (!plant) return null;
  const meta = PLANT_META[plant.id] || {};
  return {
    ...plant,
    category: getPlantCategory(plant.id),
    zone: meta.zone || '5-8',
    light: meta.light || deriveLight(plant.sun),
    water: meta.water || deriveWater(plant.watering),
    height: meta.height || null,
    careActions: meta.careActions || [],
  };
}

// Vyhledávání v databázi (case-insensitive, hledá v nameCz i nameLat)
export function searchPlants(query) {
  if (!query || query.length < 1) return [];
  const q = query.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  return PLANT_DATABASE.filter((p) => {
    const cz = p.nameCz.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    const lat = p.nameLat.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    return cz.includes(q) || lat.includes(q);
  }).slice(0, 8).map(enrichPlant);
}

// Najdi rostlinu podle přesného jména
export function findPlantByName(name) {
  if (!name) return null;
  const n = name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  const found = PLANT_DATABASE.find((p) => {
    const cz = p.nameCz.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    return cz === n || p.nameCz.toLowerCase() === name.toLowerCase();
  });
  return found ? enrichPlant(found) : null;
}
